Release 1.8 asm (#524)

diff --git a/scripts/asm-installer/install_asm b/scripts/asm-installer/install_asm
--- a/scripts/asm-installer/install_asm
+++ b/scripts/asm-installer/install_asm
@@ -384,8 +384,9 @@ configure_kubectl(){
     --project="${PROJECT_ID}" \
     --zone="${CLUSTER_LOCATION}"
 
-  if ! hash nc; then
-     warn "nc command not found, not verifying connection to Kube API server."
+  if ! hash nc 2>/dev/null; then
+     warn "nc not found, skipping k8s connection verification"
+     warn "(Installation will continue normally.)"
      return
   fi
 
@@ -1498,6 +1499,10 @@ validate_ca_consistency() {
   fi
 
   info "CA already in use: ${CURRENT_CA}"
+
+  if [[ -z "${CA}" ]]; then
+    CA="${CURRENT_CA}"
+  fi
 
   if [[ "${CA}" != "${CURRENT_CA}" ]]; then
     fatal "CA cannot be switched while performing upgrade. Please use ${CURRENT_CA} as the CA."
