Incorporating review comments

diff --git a/scripts/asm-installer/install_asm b/scripts/asm-installer/install_asm
--- a/scripts/asm-installer/install_asm
+++ b/scripts/asm-installer/install_asm
@@ -603,7 +603,7 @@ OPTIONS:
   --root_cert            <FILE PATH>
   --cert_chain           <FILE PATH>
   --ca_name              <CA NAME>
-  --revision             <CUSTOM_REVISION>
+  -r|--revision_name     <REVISION NAME>
 
 FLAGS:
   -e|--enable_all
@@ -684,11 +684,11 @@ OPTIONS:
                                       Name of the ca in the GCP CAS service used to
                                       sign certificates in the format
                                       'projects/project_name/locations/ \
-                                      ca_region/certificateAuthorities/ca_name'
-  --revision       <CUSTOM_REVISION>  Custom revision label. Label needs to follow DNS
+                                      ca_region/certificateAuthorities/ca_name'.
+  -r|--revision_name <REVISION NAME>  Custom revision label. Label needs to follow DNS
                                       label formats (re: RFC 1123). Not supported if
-                                      control plane is managed. Recommended format:
-                                      asm-<major>.<minor>.<point>-revisionTag
+                                      control plane is managed. Prefixing the revision
+                                      name with 'asm' is recommended.
   The following four options must be passed together and are only necessary
   for using a custom certificate for Citadel. Users that aren't sure whether
   they need this probably don't.
@@ -910,7 +910,7 @@ parse_args() {
         CUSTOM_CA=1
         shift 2
         ;;
-      --revision)
+      -r | --revision_name | --revision-name)
         arg_required "${@}"
         CUSTOM_REVISION=1
         REVISION_LABEL="${2}"
@@ -971,7 +971,7 @@ validate_args() {
     fi
 
     if [[ "${CUSTOM_REVISION}" -eq 1 ]]; then
-      fatal "Adding custom revision label with managed control plane is not supported"
+      fatal "Specifying a revision label with managed control plane is not supported"
     fi
   fi
 
@@ -1101,15 +1101,18 @@ EOF
 
 validate_revision_label() {
   # Matches DNS label formats of RFC 1123
-  local DNS1123LabelMaxLength; DNS1123LabelMaxLength=63
-  local DNS1123LabelFmt; DNS1123LabelFmt="[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?"
-  
-  if [[ ${#REVISION_LABEL} -gt $DNS1123LabelMaxLength ]]; then
-    fatal "Custom revision label cannot be longer than $DNS1123LabelMaxLength."
+  local DNS_1123_LABEL_MAX_LEN; DNS_1123_LABEL_MAX_LEN=63;
+  readonly DNS_1123_LABEL_MAX_LEN
+
+  local DNS_1123_LABEL_FMT; DNS_1123_LABEL_FMT="^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?$";
+  readonly DNS_1123_LABEL_FMT
+
+  if [[ ${#REVISION_LABEL} -gt ${DNS_1123_LABEL_MAX_LEN} ]]; then
+    fatal "Revision label cannot be longer than $DNS_1123_LABEL_MAX_LEN."
   fi
 
-  if ! [[ "$REVISION_LABEL" =~ $DNS1123LabelFmt ]]; then
-    fatal "Custom revision label does not follow RFC 1123 formatting convention"
+  if ! [[ "${REVISION_LABEL}" =~ ${DNS_1123_LABEL_FMT} ]]; then
+    fatal "Revision label does not follow RFC 1123 formatting convention."
   fi
 }
 
