Merge all profiles, force empty profile (#381)
* Merge all profiles, force empty profile

* Update print_config test

* Wipe namespaces before test runs

diff --git a/scripts/asm-installer/install_asm b/scripts/asm-installer/install_asm
--- a/scripts/asm-installer/install_asm
+++ b/scripts/asm-installer/install_asm
@@ -42,13 +42,14 @@ PACKAGE_DIRECTORY="asm/istio"; readonly PACKAGE_DIRECTORY;
 VALIDATION_FIX_SERVICE="${PACKAGE_DIRECTORY}/istiod-service.yaml"; readonly VALIDATION_FIX_SERVICE;
 OPTIONS_DIRECTORY="${PACKAGE_DIRECTORY}/options"; readonly OPTIONS_DIRECTORY;
 OPERATOR_MANIFEST="${PACKAGE_DIRECTORY}/istio-operator.yaml"; readonly OPERATOR_MANIFEST;
-MULTICLUSTER_MANIFEST="${OPTIONS_DIRECTORY}/multicluster.yaml"; readonly MULTICLUSTER_MANIFEST;
 BETA_CRD_MANIFEST="${OPTIONS_DIRECTORY}/v1beta1-crds.yaml"; readonly BETA_CRD_MANIFEST;
 MANAGED_MANIFEST="${OPTIONS_DIRECTORY}/managed-control-plane.yaml"; readonly MANAGED_MANIFEST;
 
 SCRIPT_NAME="${0##*/}"
 
 PROJECT_NUMBER=""
+GKE_CLUSTER_URI=""
+GCE_NETWORK_NAME=""
 KPT_URL=""
 KUBECONFIG=""
 APATH=""
@@ -900,7 +901,7 @@ EOF
   elif [[ "${CA}" = "gcp_cas" ]]; then
     ABS_OVERLAYS="${OPTIONS_DIRECTORY}/private-ca.yaml,${ABS_OVERLAYS}"
   fi
-  CUSTOM_OVERLAY="${MULTICLUSTER_MANIFEST},${ABS_OVERLAYS}"
+  CUSTOM_OVERLAY="${ABS_OVERLAYS}"
 
   set_kpt_package_url
   WORKLOAD_POOL="${PROJECT_ID}.svc.id.goog"
@@ -1130,6 +1131,21 @@ validate_gcp_resources() {
   validate_project
   PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format="value(projectNumber)")"
   validate_cluster
+}
+
+populate_cluster_values() {
+  if [[ -z "${GKE_CLUSTER_URI}" && -z "${GCE_NETWORK_NAME}" ]]; then
+    CLUSTER_DATA="$(retry 2 gcloud container clusters describe "${CLUSTER_NAME}" \
+      --zone="${CLUSTER_LOCATION}" \
+      --project="${PROJECT_ID}" \
+      --format='value(selfLink, network)')"
+    read -r GKE_CLUSTER_URI GCE_NETWORK_NAME <<EOF
+${CLUSTER_DATA}
+EOF
+
+    GCE_NETWORK_NAME="${PROJECT_ID}-${GCE_NETWORK_NAME}"
+    readonly GKE_CLUSTER_URI; readonly GCE_NETWORK_NAME;
+  fi
 }
 
 validate_project() {
@@ -1632,6 +1648,56 @@ get_cluster_labels() {
   echo "${LABELS}"
 }
 
+is_cluster_registered() {
+  local IDENTITY_PROVIDER
+  IDENTITY_PROVIDER="$(retry 2 kubectl get memberships.hub.gke.io \
+    membership -ojson 2>/dev/null | jq .spec.identity_provider)"
+
+  if [[ -z "${IDENTITY_PROVIDER}" ]] || [[ "${IDENTITY_PROVIDER}" = 'null' ]]; then
+    false
+  fi
+}
+
+generate_membership_name() {
+  local MEMBERSHIP_NAME
+  MEMBERSHIP_NAME="${CLUSTER_NAME}"
+  if [[ "$(retry 2 gcloud container hub memberships list --format='value(name)' \
+   --project "${PROJECT_ID}" | grep -c "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
+    MEMBERSHIP_NAME="${CLUSTER_NAME}-${PROJECT_ID}-${CLUSTER_LOCATION}"
+  fi
+  if [[ "${#MEMBERSHIP_NAME}" -gt 63 ]] || [[ "$(retry 2 gcloud container hub \
+   memberships list --format='value(name)' --project "${PROJECT_ID}" | grep -c \
+   "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
+    local RAND
+    RAND="$(tr -dc "a-z0-9" </dev/urandom | head -c8 || true)"
+    MEMBERSHIP_NAME="${CLUSTER_NAME:0:54}-${RAND}"
+  fi
+  echo "${MEMBERSHIP_NAME}"
+}
+
+register_cluster() {
+  if is_cluster_registered; then return; fi
+
+  populate_cluster_values
+  local MEMBERSHIP_NAME
+  MEMBERSHIP_NAME="$(generate_membership_name)"
+  info "Registering the cluster as ${MEMBERSHIP_NAME}..."
+  retry 2 run gcloud beta container hub memberships register "${MEMBERSHIP_NAME}" \
+    --project="${PROJECT_ID}" \
+    --gke-uri="${GKE_CLUSTER_URI}" \
+    --enable-workload-identity
+}
+
+exit_if_cluster_unregistered() {
+  if ! is_cluster_registered; then
+    { read -r -d '' MSG; fatal "${MSG}"; } <<EOF || true
+Cluster is not registered to an environ. Please register the cluster and
+retry, or run the script with the '--enable_registration' flag to allow
+the script to register to the current project's environ on your behalf.
+EOF
+  fi
+}
+
 is_workload_identity_enabled() {
   local ENABLED
   ENABLED="$(gcloud container clusters describe \
@@ -1761,10 +1827,12 @@ ensure_istio_namespace_exists(){
 configure_package() {
   info "Configuring kpt package..."
 
+  populate_cluster_values
   run kpt cfg set asm gcloud.container.cluster "${CLUSTER_NAME}"
   run kpt cfg set asm gcloud.core.project "${PROJECT_ID}"
   run kpt cfg set asm gcloud.project.environProjectNumber "${PROJECT_NUMBER}"
   run kpt cfg set asm gcloud.compute.location "${CLUSTER_LOCATION}"
+  run kpt cfg set asm gcloud.compute.network "${GCE_NETWORK_NAME}"
   run kpt cfg set asm anthos.servicemesh.rev "${REVISION_LABEL}"
   run kpt cfg set asm anthos.servicemesh.tag "${RELEASE}"
   if [[ -n "${_CI_ASM_IMAGE_LOCATION}" ]]; then
