modifying asm installer script to add support for custom revision tag

diff --git a/scripts/asm-installer/install_asm b/scripts/asm-installer/install_asm
--- a/scripts/asm-installer/install_asm
+++ b/scripts/asm-installer/install_asm
@@ -117,6 +117,7 @@ HUB_MEMBERSHIP_ID=""
 
 # Environment variable used by VM
 USE_VM=0
+CUSTOM_REVISION=0
 
 main() {
   init
@@ -602,6 +603,7 @@ OPTIONS:
   --root_cert            <FILE PATH>
   --cert_chain           <FILE PATH>
   --ca_name              <CA NAME>
+  --revision             <CUSTOM_REVISION>
 
 FLAGS:
   -e|--enable_all
@@ -682,7 +684,10 @@ OPTIONS:
                                       Name of the ca in the GCP CAS service used to
                                       sign certificates in the format
                                       'projects/project_name/locations/ \
-                                       ca_region/certificateAuthorities/ca_name'
+                                      ca_region/certificateAuthorities/ca_name'
+  --revision       <CUSTOM_REVISION>  Custom revision label. Label needs to follow DNS
+                                      label formats (re: RFC 1123). Not supported if
+                                      control plane is managed.
   The following four options must be passed together and are only necessary
   for using a custom certificate for Citadel. Users that aren't sure whether
   they need this probably don't.
@@ -904,6 +909,12 @@ parse_args() {
         CUSTOM_CA=1
         shift 2
         ;;
+      --revision)
+        arg_required "${@}"
+        CUSTOM_REVISION=1
+        REVISION_LABEL="${2}"
+        shift 2
+        ;;
       -v | --verbose)
         VERBOSE=1
         shift 1
@@ -933,6 +944,10 @@ validate_args() {
     CA="mesh_ca"
   fi
 
+  if [[ "${CUSTOM_REVISION}" -eq 1 ]]; then
+    validate_revision_label
+  fi
+
   if is_managed; then
     if [[ "${MODE}" != "install" ]]; then
       fatal "Migrate and upgrade are incompatible with managed control plane."
@@ -952,6 +967,10 @@ validate_args() {
 
     if [[ "${USE_VM}" -eq 1 ]]; then
       fatal "Adding VM workloads with managed control plane is not supported."
+    fi
+
+    if [[ "${CUSTOM_REVISION}" -eq 1 ]]; then
+      fatal "Adding custom revision label with managed control plane is not supported"
     fi
   fi
 
@@ -1077,6 +1096,20 @@ EOF
 
   set_kpt_package_url
   WORKLOAD_POOL="${PROJECT_ID}.svc.id.goog"
+}
+
+validate_revision_label() {
+  # Matches DNS label formats of RFC 1123
+  local DNS1123LabelMaxLength; DNS1123LabelMaxLength=63
+  local DNS1123LabelFmt; DNS1123LabelFmt="[a-zA-Z0-9]([-a-z-A-Z0-9]*[a-zA-Z0-9])?"
+  
+  if [[ ${#REVISION_LABEL} -gt $DNS1123LabelMaxLength ]]; then
+    fatal "Custom revision label cannot be longer than $DNS1123LabelMaxLength."
+  fi
+
+  if ! [[ "$REVISION_LABEL" =~ $DNS1123LabelFmt ]]; then
+    fatal "Custom revision label does not follow RFC 1123 formatting convention"
+  fi
 }
 
 validate_gcp_cas_args() {
