[1.9] Check result of runIstiod curl (#1004)
Backport of #987 to the 1.9 install_asm script. Doesn't include #995
because when 1.9 was released, asm-managed was the only available
revision.

Tested that install_asm works on a cluster.

diff --git a/scripts/asm-installer/install_asm b/scripts/asm-installer/install_asm
--- a/scripts/asm-installer/install_asm
+++ b/scripts/asm-installer/install_asm
@@ -397,6 +397,30 @@ istioctl_path() {
 }
 
 
+######
+# check_curl calls curl and returns non-zero if the http code is not 200 or the
+# curl command fails.
+######
+check_curl() {
+  local TMPFILE; TMPFILE=$(mktemp)
+
+  local HTTPCODE;
+  local RETVAL;
+  HTTPCODE=$(run curl --write-out '%{http_code}' --silent --show-error --output "$TMPFILE" "${@}")
+  RETVAL="$?"
+  if [[ "$RETVAL" != "0" ]] ; then
+    return "$RETVAL"
+  fi
+  if [[ "$HTTPCODE" != "200" ]] ; then
+    warn "HTTP response code: ${HTTPCODE}"
+  fi
+  cat "$TMPFILE"
+  if [[ "$HTTPCODE" != "200" ]] ; then
+    false
+    return
+  fi
+}
+
 #######
 # retry takes an integer N as the first argument, and a list of arguments
 # representing a command afterwards. It will retry the given command up to N
@@ -2692,7 +2716,7 @@ EOF
 )
   fi
   info "Provisioning managed control plane..."
-  retry 2 run curl --request POST \
+  retry 2 check_curl --request POST \
     "https://meshconfig.googleapis.com/v1alpha1/projects/${PROJECT_ID}/locations/${CLUSTER_LOCATION}/clusters/${CLUSTER_NAME}:runIstiod" \
     --data "${CR_IMAGE_JSON}" \
     --header "X-Server-Timeout: 600" \
