Allow asm installer to prepare VM setup (#356)
* Allow asm installer to prepare VM setup

diff --git a/scripts/asm-installer/install_asm b/scripts/asm-installer/install_asm
--- a/scripts/asm-installer/install_asm
+++ b/scripts/asm-installer/install_asm
@@ -45,10 +45,12 @@ OPERATOR_MANIFEST="${PACKAGE_DIRECTORY}/istio-operator.yaml"; readonly OPERATOR_
 MULTICLUSTER_MANIFEST="${OPTIONS_DIRECTORY}/multicluster.yaml"; readonly MULTICLUSTER_MANIFEST;
 BETA_CRD_MANIFEST="${OPTIONS_DIRECTORY}/v1beta1-crds.yaml"; readonly BETA_CRD_MANIFEST;
 MANAGED_MANIFEST="${OPTIONS_DIRECTORY}/managed-control-plane.yaml"; readonly MANAGED_MANIFEST;
+EXPOSE_ISTIOD_SERVICE="${PACKAGE_DIRECTORY}/expansion/expose-istiod.yaml"; readonly EXPOSE_ISTIOD_SERVICE;
 
 SCRIPT_NAME="${0##*/}"
 
 PROJECT_NUMBER=""
+GKE_CLUSTER_URI=""
 KPT_URL=""
 KUBECONFIG=""
 APATH=""
@@ -70,6 +72,7 @@ ENABLE_CLUSTER_LABELS="${ENABLE_CLUSTER_LABELS:=0}"
 ENABLE_GCP_APIS="${ENABLE_GCP_APIS:=0}"
 ENABLE_GCP_IAM_ROLES="${ENABLE_GCP_IAM_ROLES:=0}"
 ENABLE_GCP_COMPONENTS="${ENABLE_GCP_COMPONENTS:=0}"
+ENABLE_REGISTRATION="${ENABLE_REGISTRATION:=0}"
 
 DISABLE_CANONICAL_SERVICE="${DISABLE_CANONICAL_SERVICE:=0}"
 PRINT_CONFIG="${PRINT_CONFIG:=0}"
@@ -97,6 +100,9 @@ MANAGED_SERVICE_ACCOUNT=""
 USE_HUB_WIP=0
 ENVIRON_PROJECT_ID=""
 HUB_MEMBERSHIP_ID=""
+
+# Environment variable used by VM
+USE_VM=0
 
 main() {
   init
@@ -173,6 +179,12 @@ main() {
     exit_if_cluster_unlabeled
   fi
 
+  if can_register_cluster; then
+    register_cluster
+  elif should_validate && [[ "${USE_HUB_WIP}" -eq 1 ]]; then
+    exit_if_cluster_unregistered
+  fi
+
   if ! is_managed; then
     if can_modify_gcp_components; then
       enable_workload_identity
@@ -224,6 +236,10 @@ EOF
     install_managed_components
     outro
     return 0
+  fi
+
+  if [[ "${USE_VM}" -eq 1 ]]; then
+    register_gce_identity_provider
   fi
 
   configure_package
@@ -411,7 +427,13 @@ can_modify_gcp_iam_roles() {
 }
 
 can_modify_gcp_components() {
-  if [[ "${ENABLE_ALL}" -eq 0 && "${ENABLE_GCP_COMPONENTS}" -eq 0 ]] &&
+  if [[ "${ENABLE_ALL}" -eq 0 && "${ENABLE_GCP_COMPONENTS}" -eq 0 ]] && \
+    ! is_managed || \
+    ! can_modify_at_all; then false; fi
+}
+
+can_register_cluster() {
+  if [[ "${ENABLE_ALL}" -eq 0 && "${ENABLE_REGISTRATION}" -eq 0 ]] && \
     ! is_managed || \
     ! can_modify_at_all; then false; fi
 }
@@ -459,6 +481,7 @@ FLAGS:
      --enable_gcp_apis
      --enable_gcp_iam_roles
      --enable_gcp_components
+     --enable_registration
 
      --managed
 
@@ -560,6 +583,8 @@ FLAGS:
                                       IAM permissions
      --enable_gcp_components          Allow the script to enable required GCP
                                       managed services and components
+     --enable_registration            Allow the script to register the cluster
+                                      to an environ
 
      --managed                        Provision a remote, managed control plane
                                       instead of installing one in-cluster.
@@ -646,6 +671,9 @@ parse_args() {
         if [[ "${2}" == "hub-meshca" ]]; then
           USE_HUB_WIP=1
         fi
+        if [[ "${2}" == "vm" ]]; then
+          USE_VM=1
+        fi
         shift 2
         ;;
       --co | --custom_overlay | --custom-overlay)
@@ -675,6 +703,10 @@ parse_args() {
         ;;
       --enable_gcp_components | --enable-gcp-components)
         ENABLE_GCP_COMPONENTS=1
+        shift 1
+        ;;
+      --enable_registration | --enable-registration)
+        ENABLE_REGISTRATION=1
         shift 1
         ;;
       --managed)
@@ -786,6 +818,10 @@ validate_args() {
     if [[ "${CUSTOM_CA}" -eq 1 ]]; then
       fatal "Specifying a custom CA with managed control plane is not supported."
     fi
+
+    if [[ "${USE_VM}" -eq 1 ]]; then
+      fatal "Adding VM workloads with managed control plane is not supported."
+    fi
   fi
 
   local MISSING_ARGS=0
@@ -839,6 +875,10 @@ EOF
     fatal "Hub Workload Identity Pool is only supported for Mesh CA"
   fi
 
+  if [[ "${USE_VM}" -eq 1 && "${USE_HUB_WIP}" -eq 0 ]]; then
+    fatal "Hub Workload Identity Pool is required to add VM workloads. Run the script with the -o hub-meshca option."
+  fi
+
   if [[ "${CUSTOM_CA}" -eq 1 ]]; then
     validate_certs
   fi
@@ -856,6 +896,7 @@ ENABLE_CLUSTER_LABELS
 ENABLE_GCP_APIS
 ENABLE_GCP_IAM_ROLES
 ENABLE_GCP_COMPONENTS
+ENABLE_REGISTRATION
 MANAGED
 DISABLE_CANONICAL_SERVICE
 ONLY_VALIDATE
@@ -865,7 +906,8 @@ EOF
 
   if [[ "${ENABLE_ALL}" -eq 1 || "${ENABLE_CLUSTER_ROLES}" -eq 1 || \
     "${ENABLE_CLUSTER_LABELS}" -eq 1 || "${ENABLE_GCP_APIS}" -eq 1 || \
-    "${ENABLE_GCP_IAM_ROLES}" -eq 1 || "${ENABLE_GCP_COMPONENTS}" -eq 1 ]]; then
+    "${ENABLE_GCP_IAM_ROLES}" -eq 1 || "${ENABLE_GCP_COMPONENTS}" -eq 1 || \
+    "${ENABLE_REGISTRATION}" -eq 1 ]]; then
     if [[ "${ONLY_VALIDATE}" -eq 1 ]]; then
       fatal "The only_validate flag cannot be used with any --enable* flag"
     fi
@@ -1065,6 +1107,7 @@ kpt
 kubectl
 sed
 tr
+head
 EOF
 
   if [[ "${CUSTOM_CA}" -eq 1 ]]; then
@@ -1130,6 +1173,10 @@ validate_gcp_resources() {
   validate_project
   PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format="value(projectNumber)")"
   validate_cluster
+  GKE_CLUSTER_URI="$(retry 2 gcloud container clusters describe "${CLUSTER_NAME}" \
+    --zone="${CLUSTER_LOCATION}" \
+    --project="${PROJECT_ID}" \
+    --format='value(selfLink)')"; readonly GKE_CLUSTER_URI;
 }
 
 validate_project() {
@@ -1632,6 +1679,55 @@ get_cluster_labels() {
   echo "${LABELS}"
 }
 
+is_cluster_registered() {
+  local IDENTITY_PROVIDER
+  IDENTITY_PROVIDER="$(retry 2 kubectl get memberships.hub.gke.io \
+    membership -ojson 2>/dev/null | jq .spec.identity_provider)"
+
+  if [[ -z "${IDENTITY_PROVIDER}" ]] || [[ "${IDENTITY_PROVIDER}" = 'null' ]]; then
+    false
+  fi
+}
+
+generate_membership_name() {
+  local MEMBERSHIP_NAME
+  MEMBERSHIP_NAME="${CLUSTER_NAME}"
+  if [[ "$(retry 2 gcloud container hub memberships list --format='value(name)' \
+   --project "${PROJECT_ID}" | grep -c "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
+    MEMBERSHIP_NAME="${CLUSTER_NAME}-${PROJECT_ID}-${CLUSTER_LOCATION}"
+  fi
+  if [[ "${#MEMBERSHIP_NAME}" -gt 63 ]] || [[ "$(retry 2 gcloud container hub \
+   memberships list --format='value(name)' --project "${PROJECT_ID}" | grep -c \
+   "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
+    local RAND
+    RAND="$(tr -dc "a-z0-9" </dev/urandom | head -c8 || true)"
+    MEMBERSHIP_NAME="${CLUSTER_NAME:0:54}-${RAND}"
+  fi
+  echo "${MEMBERSHIP_NAME}"
+}
+
+register_cluster() {
+  if is_cluster_registered; then return; fi
+
+  local MEMBERSHIP_NAME
+  MEMBERSHIP_NAME="$(generate_membership_name)"
+  info "Registering the cluster as ${MEMBERSHIP_NAME}..."
+  retry 2 run gcloud beta container hub memberships register "${MEMBERSHIP_NAME}" \
+    --project="${PROJECT_ID}" \
+    --gke-uri="${GKE_CLUSTER_URI}" \
+    --enable-workload-identity
+}
+
+exit_if_cluster_unregistered() {
+  if ! is_cluster_registered; then
+    { read -r -d '' MSG; fatal "${MSG}"; } <<EOF || true
+Cluster is not registered to an environ. Please register the cluster and
+retry, or run the script with the '--enable_registration' flag to allow
+the script to register to the current project's environ on your behalf.
+EOF
+  fi
+}
+
 is_workload_identity_enabled() {
   local ENABLED
   ENABLED="$(gcloud container clusters describe \
@@ -1647,7 +1743,7 @@ is_workload_identity_enabled() {
 get_hub_workload_identity() {
   local IDENTITY_PROVIDER
   local IDENTITY
-  IDENTITY_PROVIDER="$(kubectl get memberships membership -o=json | jq .spec.identity_provider)"
+  IDENTITY_PROVIDER="$(kubectl get memberships.hub.gke.io membership -o=json | jq .spec.identity_provider)"
   IDENTITY="$(echo "${IDENTITY_PROVIDER}" | sed 's/^\"https:\/\/gkehub.googleapis.com\/projects\/\(.*\)\/locations\/global\/memberships\/\(.*\)\"$/\1 \2/g')"
   echo "${IDENTITY}"
 }
@@ -1755,6 +1851,12 @@ ensure_istio_namespace_exists(){
     info "Creating istio-system namespace..."
     retry 2 run kubectl create ns istio-system
   fi
+}
+
+register_gce_identity_provider() {
+  info "Registering GCE Identity Provider in the cluster..."
+  retry 3 run kubectl apply -f asm/identity-provider/identityprovider-crd.yaml
+  retry 3 run kubectl apply -f asm/identity-provider/googleidp.yaml
 }
 
 ### Installation functions ###
@@ -1865,6 +1967,11 @@ EOF
     retry 3 run kubectl wait --for=condition=available --timeout=600s \
         deployment/canonical-service-controller-manager -n asm-system
     info "...done!"
+  fi
+
+  if [[ "${USE_VM}" -eq 1 ]]; then
+    info "Exposing the control plane for VM workloads..."
+    retry 3 run kubectl apply -f "${EXPOSE_ISTIOD_SERVICE}"
   fi
 
   outro
