Add support for upgrading ASM to the install scripts (#190)
* Add support for upgrading ASM to the install scripts

diff --git a/scripts/asm-installer/install_asm b/scripts/asm-installer/install_asm
--- a/scripts/asm-installer/install_asm
+++ b/scripts/asm-installer/install_asm
@@ -22,7 +22,6 @@ RELEASE="${MAJOR}.${MINOR}.${POINT}-asm.${REV}"
 RELEASE_LINE="${MAJOR}.${MINOR}."
 REVISION_LABEL="asm-${MAJOR}${MINOR}${POINT}-${REV}"
 KPT_BRANCH="release-${MAJOR}.${MINOR}-asm"
-unset MAJOR; unset MINOR; unset POINT; unset REV;
 readonly RELEASE; readonly RELEASE_LINE; readonly REVISION_LABEL; readonly KPT_BRANCH;
 
 ### These are hooks for Cloud Build to be able to use debug/staging images
@@ -197,8 +196,11 @@ OPTIONS:
                                       Passing --mode install will attempt a
                                       new ASM installation. Passing --mode
                                       migrate will attempt to migrate an Istio
-                                      installation to ASM. Allowed values for
-                                      <MODE> are {install|migrate}.
+                                      installation to ASM. Passing --mode
+                                      upgrade will attempt to upgrade an
+                                      existing ASM installation to a newer
+                                      version. Allowed values for
+                                      <MODE> are {install|migrate|upgrade}.
   -c|--ca                <CA>         The type of certificate authority to be
                                       used. Defaults to "mesh_ca" for --mode
                                       install. Specifying the CA is required
@@ -371,8 +373,8 @@ EOF
 
   # shellcheck disable=SC2064
   case "${MODE}" in
-    install | migrate);;
-    *) fatal "MODE must be one of 'install', 'migrate'";;
+    install | migrate | upgrade);;
+    *) fatal "MODE must be one of 'install', 'migrate', 'upgrade'";;
   esac
 
   case "${CA}" in
@@ -475,9 +477,14 @@ validate_dependencies() {
   # kubeconfig so we're not breaking the promise that --only_validate gives
   configure_kubectl
   validate_expected_control_plane
+  
   if [[ "${MODE}" = "migrate" ]]; then
     validate_istio_version
+  elif [[ "${MODE}" = "upgrade" ]]; then
+    validate_asm_version
+    validate_ca_consistency
   fi
+
   if [[ "${ENABLE_APIS}" -eq 0 || "${ONLY_VALIDATE}" -eq 1 ]]; then
     exit_if_apis_not_enabled
   fi
@@ -661,10 +668,9 @@ EOF
 validate_expected_control_plane(){
   info "Checking Istio installations..."
   check_no_istiod_outside_of_istio_system_namespace
-  if [[ "${MODE}" = "migrate" ]]; then
+  if [[ "${MODE}" = "migrate" || "${MODE}" = "upgrade" ]]; then
     check_istio_deployed
-  fi
-  if [[ "${MODE}" = "install" ]]; then
+  elif [[ "${MODE}" = "install" ]]; then
     check_istio_not_deployed
   fi
 }
@@ -694,7 +700,7 @@ check_istio_deployed(){
   local ISTIOD_COUNT; ISTIOD_COUNT="$(get_istio_deployment_count)";
   info "Found ${ISTIOD_COUNT} deployment(s)."
   if [[ "$ISTIOD_COUNT" -eq 0 ]]; then
-    fatal "Migrate mode specified but no istiod deployment found. (Expected >=1.)"
+    fatal "${MODE} mode specified but no istiod deployment found. (Expected >=1.)"
   fi
 }
 
@@ -707,25 +713,119 @@ check_istio_not_deployed(){
 
 validate_istio_version() {
   info "Checking existing Istio version(s)..."
-  local OUTPUT
-  OUTPUT="$(retry 3 ./istio-${RELEASE}/bin/istioctl version -o json)"
-  local FOUND_VALID_VERSION
-  FOUND_VALID_VERSION="false"
-  for version in $(echo "${OUTPUT}" | jq -r '.meshVersion[].Info.version' -r); do
+  local VERSION_OUTPUT; VERSION_OUTPUT="$(retry 3 ./${ISTIOCTL_REL_PATH} version -o json)"
+  if [[ -z "${VERSION_OUTPUT}" ]]; then
+    fatal "Couldn't validate existing Istio versions."
+  fi
+  local FOUND_VALID_VERSION; FOUND_VALID_VERSION=0
+  for version in $(echo "${VERSION_OUTPUT}" | jq -r '.meshVersion[].Info.version' -r); do
     if [[ "$version" =~ ^$RELEASE_LINE ]]; then
       info "  $version (suitable for migration)"
-      FOUND_VALID_VERSION="true"
-    fi
-    if ! [[ "$version" =~ ^$RELEASE_LINE ]]; then
+      FOUND_VALID_VERSION=1
+    else
       info "  $version (not suitable for migration)"
     fi
     if [[ "$version" =~ "asm" ]]; then
       fatal "Cannot migrate from version $version. Only migration from OSS Istio to the ASM distribution is supported."
     fi
   done
-  if [[ "$FOUND_VALID_VERSION" != "true" ]]; then
+  if [[ "$FOUND_VALID_VERSION" -eq 0 ]]; then
     fatal "Migration requires an existing control plane in the ${RELEASE_LINE} line."
   fi
+}
+
+validate_asm_version() {
+  info "Checking existing ASM version(s)..."
+  local VERSION_OUTPUT; VERSION_OUTPUT="$(retry 3 ./${ISTIOCTL_REL_PATH} version -o json)"
+  if [[ -z "${VERSION_OUTPUT}" ]]; then
+    fatal "Couldn't validate existing Istio versions."
+  fi
+  local FOUND_INVALID_VERSION; FOUND_INVALID_VERSION=0
+  for VERSION in $(echo "${VERSION_OUTPUT}" | jq -r '.meshVersion[].Info.version'); do
+    if ! [[ "${VERSION}" =~ "asm" ]]; then
+      fatal "Cannot upgrade from version ${VERSION}. Only upgrades from ASM distributions are supported."
+    fi
+
+    if version_valid_for_upgrade "${VERSION}"; then
+      info "  ${VERSION} (suitable for migration)"
+    else
+      info "  ${VERSION} (not suitable for migration)"
+      FOUND_INVALID_VERSION=1
+    fi
+  done
+  if [[ "$FOUND_INVALID_VERSION" -eq 1 ]]; then
+    fatal "Upgrade requires all existing control planes to be between versions 1.$((MINOR-1)).0 (inclusive) and ${RELEASE} (exclusive)."
+  fi
+}
+
+version_valid_for_upgrade() {
+  local VERSION; VERSION=$1
+  
+  # if asm version found, pattern: 1.6.11-asm.1-586f900508ad482ed32b830dd15f6c54b32b93ed
+  local VERSION_MAJOR VERSION_MINOR VERSION_POINT VERSION_REV
+  IFS="." read -r VERSION_MAJOR VERSION_MINOR VERSION_POINT VERSION_REV <<EOF
+${VERSION}
+EOF
+  VERSION_POINT="$(sed 's/-.*//' <<EOF
+${VERSION_POINT}
+EOF
+)"
+  VERSION_REV="$(sed 's/-.*//' <<EOF
+${VERSION_REV}
+EOF
+)"
+  if is_major_minor_invalid || is_minor_point_rev_invalid; then
+    return 1
+  else
+    return 0
+  fi
+}
+
+is_major_minor_invalid() {
+  [[ "$VERSION_MAJOR" -ne 1 ]] && return 0
+  [[ "$VERSION_MINOR" -lt $((MINOR-1))  ]] && return 0
+  [[ "$VERSION_MINOR" -gt "$MINOR" ]] && return 0
+}
+
+is_minor_point_rev_invalid() {
+  [[ "$VERSION_MINOR" -eq "$MINOR" ]] && is_point_rev_invalid && return 0
+}
+
+is_point_rev_invalid() {
+  [[ "$VERSION_POINT" -gt "$POINT" ]] && return 0
+  is_rev_invalid && return 0
+}
+
+is_rev_invalid() {
+  [[ "$VERSION_POINT" -eq "$POINT" && "$VERSION_REV" -ge "$REV" ]] && return 0
+}
+
+validate_ca_consistency() {
+  info "Checking existing CA..."
+  local INSTALLED_CA; INSTALLED_CA="$(kubectl -n istio-system get pod -l istio=ingressgateway \
+    -o jsonpath='{.items[].spec.containers[].env[?(@.name=="CA_ADDR")].value}')"
+  
+  local CURRENT_CA; CURRENT_CA=citadel
+  if is_meshca_installed; then
+    CURRENT_CA=mesh_ca
+  fi
+  info "CA already in use: ${CURRENT_CA}"
+
+  if is_ca_citadel_to_meshca || is_ca_meshca_to_citadel; then
+    fatal "CA cannot be switched while performing upgrade. Please use ${CURRENT_CA} as the CA."
+  fi
+}
+
+is_ca_citadel_to_meshca() {
+  ! is_meshca_installed && [[ "${CA}" = "mesh_ca" ]] && return 0
+}
+
+is_ca_meshca_to_citadel() {
+  is_meshca_installed && [[ "${CA}" = "citadel" ]] && return 0
+}
+
+is_meshca_installed() {
+  [[ "${INSTALLED_CA}" =~ meshca\.googleapis\.com ]] && return 0
 }
 
 ### Project functions ###
