addressing comments

diff --git a/scripts/asm-installer/release_asm_installer b/scripts/asm-installer/release_asm_installer
--- a/scripts/asm-installer/release_asm_installer
+++ b/scripts/asm-installer/release_asm_installer
@@ -18,14 +18,12 @@ BUCKET_PATH="csm-artifacts/asm"; readonly BUCKET_PATH
 
 CURRENT_RELEASE="release-1.9-asm"; readonly CURRENT_RELEASE
 
-ALWAYS_PUBLISH_VERSION="${ALWAYS_PUBLISH_VERSION:=0}"
 STABLE_VERSION_FILE="STABLE_VERSIONS"; readonly STABLE_VERSION_FILE
-VERSION_FILE_PATH="${BUCKET_PATH}/${STABLE_VERSION_FILE}"
-HOLD_TYPE="temp"
+STABLE_VERSION_FILE_PATH="${BUCKET_PATH}/${STABLE_VERSION_FILE}"; readonly STABLE_VERSION_FILE_PATH
+HOLD_TYPE="temp"; readonly HOLD_TYPE
 trap 'gsutil retention "${HOLD_TYPE}" release gs://"${VERSION_FILE_PATH}"' ERR  # make sure the hold is cleared
 
 main() {
-  parse_args "${@}"
   setup
 
   while read -r branch version; do
@@ -128,25 +126,21 @@ get_stable_version() {
 }
 
 get_version_file_and_lock() {
-  local FILE_PATH; FILE_PATH=${BUCKET_PATH}/${STABLE_VERSION_FILE}
-
-  if [[ ! $(curl -O "${BUCKET_URL}/${FILE_PATH}") ]]; then
-    echo "Create New Version File ${STABLE_VERSION_FILE}"
-    true >| ${STABLE_VERSION_FILE}
-    gsutil cp "${STABLE_VERSION_FILE}" gs://"${FILE_PATH}"
+  if ! gsutil -q stat "gs://${STABLE_VERSION_FILE_PATH}"; then
+    echo "[ERROR]: file does not exist: ${STABLE_VERSION_FILE_PATH}." >&2
+    exit 2
   fi
 
-  gsutil retention ${HOLD_TYPE} set "gs://${FILE_PATH}"
+  gsutil retention "${HOLD_TYPE}" set "gs://${STABLE_VERSION_FILE_PATH}"
 }
 
 upload_version_file_and_unlock() {
-  local FILE_PATH; FILE_PATH=${BUCKET_PATH}/${STABLE_VERSION_FILE}
+  TMPFILE="$(mktemp)"
+  sort -r "${STABLE_VERSION_FILE}" | uniq >> "${TMPFILE}" && mv "${TMPFILE}" "${STABLE_VERSION_FILE}"
 
-  sort -r ${STABLE_VERSION_FILE} | uniq > "tmpfile" && mv "tmpfile" ${STABLE_VERSION_FILE}
-
-  gsutil retention ${HOLD_TYPE} release gs://"${FILE_PATH}"
-  gsutil cp "${STABLE_VERSION_FILE}" gs://"${FILE_PATH}"
-  gsutil acl ch -u AllUsers:R gs://"${FILE_PATH}"
+  gsutil retention "${HOLD_TYPE}" release gs://"${STABLE_VERSION_FILE_PATH}"
+  gsutil cp "${STABLE_VERSION_FILE}" gs://"${STABLE_VERSION_FILE_PATH}"
+  gsutil acl ch -u AllUsers:R gs://"${STABLE_VERSION_FILE_PATH}"
 }
 
 upload() {
@@ -189,25 +183,25 @@ write_and_upload() {
   local FILE_PATH; FILE_PATH="${BUCKET_PATH}/${FILE_NAME}"
   local FILE_URI; FILE_URI="${BUCKET_URL}/${FILE_PATH}"
 
-  if changes_necessary "${FILE_URI}" "${FILE_NAME}"; then
-    sha256sum "${SCRIPT_NAME}" >| "${SCRIPT_NAME}.sha256"
-    cp "${SCRIPT_NAME}" "${FILE_NAME}"
-    sha256sum "${FILE_NAME}" >> "${SCRIPT_NAME}.sha256"
+  if ! changes_necessary "${FILE_URI}" "${FILE_NAME}"; then return; fi
 
-    upload "${SCRIPT_NAME}" "${FILE_NAME}" "${FILE_PATH}" "${FILE_URI}"
+  sha256sum "${SCRIPT_NAME}" >| "${SCRIPT_NAME}.sha256"
+  cp "${SCRIPT_NAME}" "${FILE_NAME}"
+  sha256sum "${FILE_NAME}" >> "${SCRIPT_NAME}.sha256"
 
-    if [[ "${BRANCH_NAME}" == "${CURRENT_RELEASE}" ]]; then
-      upload "${SCRIPT_NAME}" "${FILE_NAME}" "${BUCKET_PATH}/${SCRIPT_NAME}" "${BUCKET_URL}/${BUCKET_PATH}/${SCRIPT_NAME}"
-    fi
+  upload "${SCRIPT_NAME}" "${FILE_NAME}" "${FILE_PATH}" "${FILE_URI}"
 
-    git restore "${SCRIPT_NAME}"
+  if [[ "${BRANCH_NAME}" == "${CURRENT_RELEASE}" ]]; then
+    upload "${SCRIPT_NAME}" "${FILE_NAME}" "${BUCKET_PATH}/${SCRIPT_NAME}" "${BUCKET_URL}/${BUCKET_PATH}/${SCRIPT_NAME}"
+  fi
 
-    append_version "$(./"${SCRIPT_NAME}" --version)" "${FILE_NAME}"
-
-    echo "Published ${FILE_NAME} successfully."
-  elif [[ ${ALWAYS_PUBLISH_VERSION} -eq 1 ]]; then
+  if [[ "${BRANCH_NAME}" =~ "release" ]]; then
     append_version "$(./"${SCRIPT_NAME}" --version)" "${FILE_NAME}"
   fi
+
+  git restore "${SCRIPT_NAME}"
+
+  echo "Published ${FILE_NAME} successfully."
 }
 
 append_version() {
@@ -229,19 +223,4 @@ setup() {
   get_version_file_and_lock
 }
 
-parse_args() {
-  # shellcheck disable=SC2064
-  trap "$(shopt -p nocasematch)" RETURN
-  shopt -s nocasematch
-
-  while [[ $# != 0 ]]; do
-    case "${1}" in
-      -a | --always_publish_version)
-        ALWAYS_PUBLISH_VERSION=1
-        shift 1
-        ;;
-    esac
-  done
-}
-
-main "${@}"
+main
