add check trust anchor and fix some typos (#1221)

diff --git a/scripts/migration/ca-migration/ca_migration_cli b/scripts/migration/ca-migration/ca_migration_cli
--- a/scripts/migration/ca-migration/ca_migration_cli
+++ b/scripts/migration/ca-migration/ca_migration_cli
@@ -41,10 +41,10 @@ arg_required() {
 kube() {
   local KUBECTL_CONTEXT; KUBECTL_CONTEXT="$(context_get-option "CONTEXT")"
   local KUBECONFIG; KUBECONFIG="$(context_get-option "KUBECONFIG")"
-  if [[ -z "${KUBECONFIG}" ]]; do
-    kubectl ${@}
+  if [[ -z "${KUBECONFIG}" ]]; then
+    kubectl "${@}"
   else
-    kubectl --kubeconfig=${KUBECONFIG} --context=${KUBECTL_CONTEXT} ${@}
+    kubectl --kubeconfig=${KUBECONFIG} --context=${KUBECTL_CONTEXT} "${@}"
   fi
 }
 
@@ -53,6 +53,7 @@ check_empty_args() {
     arg_val="$(context_get-option "${arg}")" 
     if [[ -z "${arg_val}" ]]; then
       error "arg ${arg} missing"
+    fi
   done
 }
 
@@ -130,7 +131,7 @@ set_up_local_workspace() {
 
 
 context_init() {
-  local CONTEXT_JSON; CONTEXT_JSON=$(cat <<EOF
+  local CONTEXT_JSON; CONTEXT_JSON=$(cat <<-EOF
 {
   "flags": {
     "KUBECONFIG": "${KUBECONFIG:-}",
@@ -144,7 +145,7 @@ context_init() {
     "NAMESPACES": "${NAMESPACES:-}",
     "CA_CERT": "${CA_CERT:-}",
     "FORCE": "${FORCE:-}",
-    "RELEASE": "${RELEASE:-}",
+    "RELEASE": "${RELEASE:-}"
   }
 }
 EOF
@@ -152,7 +153,6 @@ EOF
 
   context_FILE_LOCATION="$(mktemp)"; readonly context_FILE_LOCATION
   export context_FILE_LOCATION
-
   echo "${CONTEXT_JSON}" | jq -S '.' >| "${context_FILE_LOCATION}"
 }
 
@@ -458,13 +458,97 @@ add-trust-anchor_subcommand() {
   parse_args "${@}"
   check_empty_args "CA_CERT" "FLEET_ID" "REVISION"
   warn "add-trust-anchor-to-be-implemented"
+  update_migration_cr "TRUSTANCHOR_INJECTED"
 }
 
 #TODO: Check if new CA trust anchor has reached all workloads in all clusters of the same mesh
 check-trust-anchor_subcommand() {
   parse_args "${@}"
   check_empty_args "CA_CERT" "FLEET_ID" "REVISION" "NAMESPACES"
-  warn "check-trust-anchor-to-be-implemented"
+  local CA_CERT; CA_CERT="$(context_get-option "CA_CERT")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
+  local REVISION; REVISION="$(context_get-option "REVISION")"
+  local NAMESPACES; NAMESPACES="$(context_get-option "NAMESPACES")"
+  IFS=',' read -ra NAMESPACE_LIST <<< "$NAMESPACES"
+  for ns in "${NAMESPACE_LIST[@]}"; do
+    echo "Check the CA cert in namespace ${ns}"
+    check_in_namespace "${ns}" "cert" "ROOTCA" "${CA_CERT}"
+  done
+  update_migration_cr "TRUSTANCHOR_CHECKED"
+}
+
+# $1: namespace
+# $2: cert/other subcommand
+# $3: roots/certs
+# $4: caCert filename
+check_in_namespace() {
+  local pods
+  local containers
+
+  pods=$(kube get pod -o jsonpath={.items..metadata.name} -n "$1")
+	for pod in ${pods}
+	do
+    containers=$(kube get pod "${pod}" -n "$1" -o jsonpath=={.spec.containers.*.name})
+    if [[ "${containers}" == *"istio-proxy"* ]]; then
+      if [[ "$2" = "cert" ]]; then
+        check_cert_in_pod "${pod}" "$1" "$3" "$4"
+      fi
+    fi
+	done
+}
+
+declare -A rootmap
+
+add_to_rootmap() {
+  local output
+  local roots
+
+  output=$(istioctl pc secret "$1" -n "$2" -o json)
+
+  if [ "$(echo "${output}" | jq '.dynamicActiveSecrets[0].name')" = "\"ROOTCA\"" ]; then
+    roots=$(echo "${output}" | jq '.dynamicActiveSecrets[0].secret.validationContext.trustedCa.inlineBytes')
+  else
+    roots=$(echo "${output}" | jq '.dynamicActiveSecrets[1].secret.validationContext.trustedCa.inlineBytes')
+  fi
+  if [ -z "${roots}" ]; then
+    echo "Cannot find roots for $1.$2"
+    exit 1
+  fi
+  echo "${roots}" | sed 's/\"//g' | base64 -d > /tmp/"$3".pem
+  # Search for trustAnchor in workload trustBundle
+  if [[ "$CACERT" = "$(grep -f /tmp/"$3".pem <(echo "$CACERT"))" ]]; then
+    rootmap[$3]=true
+  else
+    rootmap[$3]=false
+  fi
+}
+
+# $1: pod
+# $2: namespace
+# $3: ROOTCA/default
+# $4: caCert file
+check_cert_in_pod() {
+  local sn
+
+  # Example format:
+  # RESOURCE NAME   TYPE   STATUS   VALID CERT  SERIAL NUMBER        NOT AFTER            NOT BEFORE
+  # ROOTCA          CA     ACTIVE   true        16289816804573236346 2117-12-31T19:15:51Z 2018-01-24T19:15:51Z
+  # We use the serial number for the comparison.
+  if [ "$3" = "ROOTCA" ]; then
+    sn=$(istioctl pc secret "$1" -n "$2" | grep "ROOTCA" | awk '{print $5}')
+    if [[ -z ${sn} ]]; then
+      echo " - [WARNING] $1.$2 cannot find certificate information"
+      return
+    fi
+    if [[ -z ${rootmap[${sn}]} ]]; then
+      add_to_rootmap "$1" "$2" "${sn}" "$4"
+    fi
+    if ! ${rootmap[${sn}]}; then
+      echo "$1.$2 does not trust $4"
+    else
+      echo "$1.$2 trusts $4"
+    fi
+  fi
 }
 
 #TODO: Change CA configuration
