add trust anchor subcommand (#1224)

diff --git a/scripts/migration/ca-migration/ca_migration_cli b/scripts/migration/ca-migration/ca_migration_cli
--- a/scripts/migration/ca-migration/ca_migration_cli
+++ b/scripts/migration/ca-migration/ca_migration_cli
@@ -329,6 +329,7 @@ $AGCLOUD
 git
 grep
 jq
+yq
 $AKUBECTL
 sed
 tr
@@ -457,8 +458,21 @@ initialize_subcommand() {
 add-trust-anchor_subcommand() {
   parse_args "${@}"
   check_empty_args "CA_CERT" "FLEET_ID" "REVISION"
-  warn "add-trust-anchor-to-be-implemented"
+  add_trust_anchor
   update_migration_cr "TRUSTANCHOR_INJECTED"
+}
+
+add_trust_anchor() {
+  local REVISION; REVISION="$(context_get-option "REVISION")"
+  local REV_NAME; REV_NAME="istio-${REVISION}"
+  local CA_CERT; CA_CERT="$(context_get-option "CA_CERT")"
+  if [[ "${REVISION}" = default ]]; then
+    REV_NAME="istio"
+  fi
+  info "Adding new CA trust anchor to ${REV_NAME} configmap"
+  local CA_CERT_CONTENT; CA_CERT_CONTENT=$(cat "$CA_CERT")
+  local NEW_MESH_CONFIG; NEW_MESH_CONFIG=$(kube -n istio-system get configmaps ${REV_NAME} -o jsonpath='{.data.mesh}' | yq eval -o=json | jq '.caCertificates[.caCertificates| length] |= . + {"pem": "'"$CA_CERT_CONTENT"'"}' | yq eval -P)
+  kube -n istio-system get configmaps ${REV_NAME} -o json | jq --arg NEW_MESH_CONFIG "$NEW_MESH_CONFIG" '.data.mesh = $NEW_MESH_CONFIG' | yq eval -P | kube apply -f - || warn "failed to patch the configmap ${REV_NAME}"
 }
 
 #TODO: Check if new CA trust anchor has reached all workloads in all clusters of the same mesh
