addon-migration: Ensure istioctl is locally installed

diff --git a/scripts/migration/migrate-addon b/scripts/migration/migrate-addon
--- a/scripts/migration/migrate-addon
+++ b/scripts/migration/migrate-addon
@@ -178,7 +178,7 @@ print_intro() {
 check_prerequisites() {
   echo -e "${blue}Checking prerequisites...${clr}"
   command -v kubectl >| /dev/null 2>&1 || die "kubectl must be installed, aborting."
-  command -v istioctl >| /dev/null 2>&1 || die "istioctl must be installed, aborting."
+  command -v ./istioctl >| /dev/null 2>&1 || die "istioctl must be installed in the local directory, aborting."
   echo -e "${green}OK${clr}"
 }
 
@@ -355,7 +355,7 @@ rollback_gateway() {
 replace_webhook() {
   prompt "Configuring sidecar injection to use Anthos Service Mesh by default..."
   kube patch mutatingwebhookconfigurations istio-sidecar-injector --type=json -p='[{"op": "replace", "path": "/webhooks"}]'
-  istioctl x revision tag set default --revision=asm-managed-rapid --overwrite
+  ./istioctl x revision tag set default --revision=asm-managed-rapid --overwrite
   echo -e "${green}OK${clr}"
 }
 
