Migration script tweaks for MCP (#892)
* Rename migration script

* Bump version, add supported mcp regions

* Run the assessment

* Add checks

* Add no-mcp flag

* Update meshconfig init logic

* Add init logic

* Better logging, use empty profile

diff --git a/scripts/migration/migrate-to-asm b/scripts/migration/migrate-to-asm
--- a/scripts/migration/migrate-to-asm
+++ b/scripts/migration/migrate-to-asm
@@ -13,6 +13,7 @@ DRY_RUN=0
 VERBOSE=0
 ENABLE_DEPENDENCIES=0
 UPGRADE_GATEWAYS=1
+NO_MCP=0
 CUSTOM_OVERLAY=""
 
 CONFIGURED=0
@@ -23,14 +24,20 @@ RELABEL=0
 FINALIZE=0
 ROLLBACK=0
 
-ASM_VERSION="1.10.2-asm.2"
+ASM_VERSION="1.10.4-asm.4"
 KPT_URL="https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages"
 KPT_URL="${KPT_URL}.git/asm@release-1.10-asm"; readonly KPT_URL
-REVISION_LABEL="asm-1102-2"; readonly REVISION_LABEL
+
+REVISION_LABEL="asm-1104-4"; readonly REVISION_LABEL
 ISTIO_FOLDER_NAME="istio-${ASM_VERSION}"; readonly ISTIO_FOLDER_NAME;
+BASE_REL_PATH="${ISTIO_FOLDER_NAME}/manifests/charts/base/files/gen-istio-cluster.yaml"; readonly BASE_REL_PATH;
 ISTIOCTL_REL_PATH="${ISTIO_FOLDER_NAME}/bin/istioctl"; readonly ISTIOCTL_REL_PATH;
 PACKAGE_DIRECTORY="asm/istio"; readonly PACKAGE_DIRECTORY;
+CRD_CONTROL_PLANE_REVISION="asm/control-plane-revision/crd.yaml"; readonly CRD_CONTROL_PLANE_REVISION;
+CR_CONTROL_PLANE_REVISION_REGULAR="asm/control-plane-revision/cr_regular.yaml"; readonly CR_CONTROL_PLANE_REVISION_REGULAR;
 NO_DEFAULT_INGRESS="${PACKAGE_DIRECTORY}/options/no-default-ingress.yaml"; readonly NO_DEFAULT_INGRESS;
+MANAGED_CNI="${PACKAGE_DIRECTORY}/options/cni-managed.yaml"; readonly MANAGED_CNI;
+MANAGED_WEBHOOKS="${PACKAGE_DIRECTORY}/options/managed-control-plane-webhooks.yaml"; readonly MANAGED_WEBHOOKS;
 CNI_MANIFEST="${PACKAGE_DIRECTORY}/options/cni-gcp.yaml"; readonly CNI_MANIFEST;
 OPERATOR_MANIFEST="${PACKAGE_DIRECTORY}/istio-operator.yaml"; readonly OPERATOR_MANIFEST;
 CANONICAL_CONTROLLER_MANIFEST="asm/canonical-service/controller.yaml"; readonly CANONICAL_CONTROLLER_MANIFEST;
@@ -199,6 +206,9 @@ FLAGS:
   --enable-dependencies          Allow this tool to enable dependencies on
                                  your behalf.
   --no-gateways                  Skip upgrading gateways.
+  --no-mcp                       Always install the control plane into the
+                                 cluster instead of using a Google-managed
+                                 control plane.
   --dry-run                      Any commands that would have side effects
                                  are skipped and instead printed.
   --verbose                      Print all commands before running.
@@ -277,6 +287,10 @@ parse_args() {
         ;;
       --no-gateways | --no_gateways)
         UPGRADE_GATEWAYS=0
+        shift 1
+        ;;
+      --no-mcp | --no_mcp)
+        NO_MCP=1
         shift 1
         ;;
       --dry-run | --dry_run)
@@ -570,10 +584,11 @@ download_asm() {
   local TARBALL; TARBALL="istio-${ASM_VERSION}-${OS}.tar.gz"
   curl -L "https://storage.googleapis.com/gke-release/asm/${TARBALL}" \
     | tar xz
+
   info "Downloaded to ${ISTIO_FOLDER_NAME}"
 
   info "Downloading ASM kpt package to the 'asm' directory..."
-  retry 3 kpt pkg get --auto-set=false "${KPT_URL}" asm
+  retry 3 "${AKPT}" pkg get --auto-set=false "${KPT_URL}" asm
 }
 
 populate_cluster_values() {
@@ -625,6 +640,14 @@ backup_config() {
   fi
 }
 
+asm_revision_label() {
+  if should_use_mcp; then
+    echo "asm_managed"
+  else
+    echo "${REVISION_LABEL}"
+  fi
+}
+
 current_label() {
   if [[ -s configuration_backup/label ]]; then
     cat configuration_backup/label
@@ -648,6 +671,9 @@ enable_dependencies() {
   enable_service_mesh_feature
   enable_stackdriver_kubernetes
   add_cluster_labels
+  if should_use_mcp; then
+    return # init meshconfig happens at install time
+  fi
   bind_user_to_cluster_admin
   init_meshconfig
 }
@@ -658,6 +684,38 @@ gkehub.googleapis.com
 stackdriver.googleapis.com
 meshconfig.googleapis.com
 meshca.googleapis.com
+EOF
+}
+
+supported_mcp_regions() {
+  cat << EOF
+asia-east1
+asia-east2
+asia-northeast1
+asia-northeast2
+asia-northeast3
+asia-southeast1
+asia-southeast2
+asia-south1
+asia-south2
+australia-southeast1
+australia-southeast2
+europe-central2
+europe-north1
+europe-west1
+europe-west2
+europe-west3
+europe-west6
+europe-west4
+northamerica-northeast1
+southamerica-east1
+us-central1
+us-east1
+us-east4
+us-west1
+us-west2
+us-west3
+us-west4
 EOF
 }
 
@@ -1060,19 +1118,102 @@ ensure_backup() {
 configure_package() {
   info "Configuring kpt package..."
 
-  run kpt cfg set asm gcloud.container.cluster "${CLUSTER_NAME}"
-  run kpt cfg set asm gcloud.core.project "${PROJECT_ID}"
-  run kpt cfg set asm gcloud.project.environProjectNumber "${FLEET_PROJECT_NUMBER}"
-  run kpt cfg set asm gcloud.compute.location "${CLUSTER_LOCATION}"
-  run kpt cfg set asm gcloud.compute.network "${GCE_NETWORK_NAME}"
-  run kpt cfg set asm anthos.servicemesh.rev "${REVISION_LABEL}"
-  run kpt cfg set asm anthos.servicemesh.tag "${ASM_VERSION}"
-  run kpt cfg set asm anthos.servicemesh.hubTrustDomain "${FLEET_PROJECT_ID}.svc.id.goog"
+  run "${AKPT}" cfg set asm gcloud.container.cluster "${CLUSTER_NAME}"
+  run "${AKPT}" cfg set asm gcloud.core.project "${PROJECT_ID}"
+  run "${AKPT}" cfg set asm gcloud.project.environProjectNumber "${FLEET_PROJECT_NUMBER}"
+  run "${AKPT}" cfg set asm gcloud.compute.location "${CLUSTER_LOCATION}"
+  run "${AKPT}" cfg set asm gcloud.compute.network "${GCE_NETWORK_NAME}"
+  run "${AKPT}" cfg set asm anthos.servicemesh.rev "$(asm_revision_label)"
+  run "${AKPT}" cfg set asm anthos.servicemesh.tag "${ASM_VERSION}"
+  run "${AKPT}" cfg set asm anthos.servicemesh.hubTrustDomain "${FLEET_PROJECT_ID}.svc.id.goog"
   HUB_IDP_URL="$(kubectl get memberships.hub.gke.io membership -o=jsonpath='{.spec.identity_provider}' || true)"
-  run kpt cfg set asm anthos.servicemesh.hub-idp-url "${HUB_IDP_URL}"
-  run kpt cfg set asm anthos.servicemesh.trustDomainAliases \
+  run "${AKPT}" cfg set asm anthos.servicemesh.hub-idp-url "${HUB_IDP_URL}"
+  run "${AKPT}" cfg set asm anthos.servicemesh.trustDomainAliases \
     "${FLEET_PROJECT_ID}.svc.id.goog" "${FLEET_PROJECT_ID}.hub.id.goog"
   info "Configured."
+}
+
+scrape_managed_urls() {
+  local URL
+  URL="$(kubectl get mutatingwebhookconfiguration istiod-asm-managed -ojson | jq .webhooks[0].clientConfig.url -r)"
+  # shellcheck disable=SC2001
+  VALIDATION_URL="$(echo "${URL}" | sed 's/inject.*$/validate/g')"
+  # shellcheck disable=SC2001
+  CLOUDRUN_ADDR=$(echo "${URL}" | cut -d'/' -f3)
+
+  echo "${VALIDATION_URL} ${CLOUDRUN_ADDR}"
+}
+
+install_mcp() {
+  init_meshconfig
+
+  info "Configuring base installation for managed control plane..."
+  run kubectl apply --overwrite=true -f "${BASE_REL_PATH}"
+
+  info "Configuring ASM managed control plane revision CRD..."
+  run kubectl apply --overwrite=true -f "${CRD_CONTROL_PLANE_REVISION}"
+
+  local ASM_OPTS
+  ASM_OPTS="$(kubectl -n istio-system \
+    get --ignore-not-found cm asm-options \
+    -o jsonpath='{.data.ASM_OPTS}' || true)"
+
+  local CNI; CNI="off"
+  if [[ -z "${ASM_OPTS}" ]]; then CNI="on"; fi
+
+  if [[ -z "${ASM_OPTS}" || "${ASM_OPTS}" != *"CNI=${CNI}"* ]]; then
+    info "Configuring control plane options..."
+    run kubectl apply --overwrite=true -f - <<EOF
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: asm-options
+  namespace: istio-system
+data:
+  ASM_OPTS: "CNI=${CNI}"
+EOF
+  fi
+
+  info "Provisioning managed control plane..."
+  retry 2 run curl --request POST \
+    "https://meshconfig.googleapis.com/v1alpha1/projects/${PROJECT_ID}/locations/${CLUSTER_LOCATION}/clusters/${CLUSTER_NAME}:runIstiod" \
+    --data "" \
+    --header "X-Server-Timeout: 600" \
+    --header "Content-Type: application/json" \
+    -K <(auth_header "$(get_auth_token)")
+
+  configure_package
+
+  local VALIDATION_URL; local CLOUDRUN_ADDR;
+  read -r VALIDATION_URL CLOUDRUN_ADDR <<EOF
+$(retry 5 scrape_managed_urls)
+EOF
+
+  if [[ -z "${VALIDATION_URL}" ]] || [[ -z "${CLOUDRUN_ADDR}" ]]; then
+    fatal "Failed to read configuration to install components for managed control plane!"
+  fi
+
+  kpt cfg set asm anthos.servicemesh.controlplane.validation-url "${VALIDATION_URL}"
+  kpt cfg set asm anthos.servicemesh.managed-controlplane.cloudrun-addr "${CLOUDRUN_ADDR}"
+
+  info "Installing CNI controller..."
+  run kubectl apply -f "${MANAGED_CNI}"
+
+  info "Configuring ASM managed control plane validating webhook config..."
+  run kubectl apply -f "${MANAGED_WEBHOOKS}"
+
+  info "Configuring ASM managed control plane revision CR for regular channel..."
+  run kubectl apply -f "${CR_CONTROL_PLANE_REVISION_REGULAR}"
+
+  info "Installing canonical service controller..."
+  run kubectl apply -f "${CANONICAL_CONTROLLER_MANIFEST}"
+  retry 2 run kubectl wait --for=condition=available --timeout=600s \
+      deployment/canonical-service-controller-manager -n asm-system
+
+  info ""
+  info "*******"
+  info "Control plane installation complete!"
 }
 
 install_asm() {
@@ -1085,7 +1226,7 @@ install_asm() {
     PARAMS="${PARAMS} -f ${NO_DEFAULT_INGRESS}"
   fi
   PARAMS="${PARAMS} -c ${KUBECONFIG}"
-  PARAMS="${PARAMS} --set revision=${REVISION_LABEL}"
+  PARAMS="${PARAMS} --set revision=$(asm_revision_label)"
   PARAMS="${PARAMS} --skip-confirmation"
 
   info "Installing ASM control plane..."
@@ -1095,8 +1236,8 @@ install_asm() {
   # Prevent the stderr buffer from ^ messing up the terminal output below
   sleep 1
 
-  local RAW_YAML; RAW_YAML="${REVISION_LABEL}-manifest-raw.yaml"
-  local EXPANDED_YAML; EXPANDED_YAML="${REVISION_LABEL}-manifest-expanded.yaml"
+  local RAW_YAML; RAW_YAML="$(asm_revision_label)-manifest-raw.yaml"
+  local EXPANDED_YAML; EXPANDED_YAML="$(asm_revision_label)-manifest-expanded.yaml"
 
   PARAMS="-f ${OPERATOR_MANIFEST}"
   if [[ "${UPGRADE_GATEWAYS}" -eq 0 ]]; then
@@ -1119,13 +1260,30 @@ install_asm() {
 }
 
 init_meshconfig() {
-  if [[ "${FLEET_PROJECT_ID}" != "${PROJECT_ID}" ]]; then return; fi
-
   info "Initializing meshconfig API..."
+  local POST_DATA
+
+  if should_use_mcp; then
+    POST_DATA='{"workloadIdentityPools":["'${FLEET_PROJECT_ID}'.hub.id.goog","'${FLEET_PROJECT_ID}'.svc.id.goog"], "prepare_istiod": true}'
+  else
+    POST_DATA='{"workloadIdentityPools":["'${FLEET_PROJECT_ID}'.hub.id.goog","'${FLEET_PROJECT_ID}'.svc.id.goog"], "prepare_istiod": false}'
+  fi
+
   run curl --request POST --fail \
-  --data '' -o /dev/null \
-  "https://meshconfig.googleapis.com/v1alpha1/projects/${PROJECT_ID}:initialize" \
-  -K <(auth_header "$(get_auth_token)")
+    --data "${POST_DATA}" -o /dev/null \
+    "https://meshconfig.googleapis.com/v1alpha1/projects/${FLEET_PROJECT_ID}:initialize" \
+    --header "X-Server-Timeout: 600" \
+    --header "Content-Type: application/json" \
+    -K <(auth_header "$(get_auth_token)")
+
+  if [[ "${FLEET_PROJECT_ID}" != "${PROJECT_ID}" ]]; then
+    run curl --request POST --fail \
+      --data "${POST_DATA}" -o /dev/null \
+      "https://meshconfig.googleapis.com/v1alpha1/projects/${PROJECT_ID}:initialize" \
+      --header "X-Server-Timeout: 600" \
+      --header "Content-Type: application/json" \
+      -K <(auth_header "$(get_auth_token)")
+  fi
 }
 
 get_auth_token() {
@@ -1160,7 +1318,7 @@ EOF
       *     )
         info "Migration canceled. You can re-run migration via this tool at any time."
         info "Migration can also be completed manually by labeling namespaces with"
-        info "${REVISION_LABEL} and restarting workloads, then using this tool to finalize."
+        info "$(asm_revision_label) and restarting workloads, then using this tool to finalize."
         exit 2
       ;;
     esac
@@ -1169,7 +1327,7 @@ EOF
     info "For --dry-run, continuing automatically."
   fi
 
-  relabel_namespaces_restart_workloads "istio.io/rev=${REVISION_LABEL}"
+  relabel_namespaces_restart_workloads "istio.io/rev=$(asm_revision_label)"
 }
 
 relabel_for_rollback() {
@@ -1260,11 +1418,11 @@ finalize() {
 }
 
 set_default_tag() {
-  info "Setting ${REVISION_LABEL} as the target for \"istio-injection=enabled\"..."
+  info "Setting $(asm_revision_label) as the target for \"istio-injection=enabled\"..."
   kubectl patch mutatingwebhookconfigurations istio-sidecar-injector \
     --type=json -p='[{"op": "replace", "path": "/webhooks"}]'
   run istioctl x revision tag \
-    set default --revision="${REVISION_LABEL}" \
+    set default --revision="$(asm_revision_label)" \
     --overwrite
 }
 
@@ -1337,11 +1495,100 @@ apply_backup() {
 }
 
 remove_asm() {
-  run istioctl x uninstall --revision "${REVISION_LABEL}" -y
+  run istioctl x uninstall --revision "$(asm_revision_label)" -y
   run kubectl delete ns asm-system
 
   info "****"
   info "Anthos Service Mesh has been uninstalled from the cluster."
+}
+
+should_use_mcp() {
+  if [[ "${NO_MCP}" -eq 1 ]]; then false; return; fi
+  if [[ -f ./configuration_backup/use_mcp ]]; then return; fi
+  if [[ -f ./configuration_backup/no_use_mcp ]]; then false; return; fi
+
+  run_mcp_fit_assessment
+}
+
+is_private_cluster() {
+  gcloud container clusters describe \
+    --region "${CLUSTER_LOCATION}" \
+    --project "${PROJECT_ID}" \
+    "${CLUSTER_NAME}" --format json \
+    | grep -q '"enablePrivateEndpoint": true,'
+}
+
+is_autopilot() {
+  gcloud container clusters describe \
+    --region "${CLUSTER_LOCATION}" \
+    --project "${PROJECT_ID}" \
+    "${CLUSTER_NAME}" --format json \
+    | grep -q 'autopilot'
+}
+
+is_supported_location() {
+  while read -r region; do
+    if [[ "${CLUSTER_LOCATION}" = "${region}"* ]]; then
+      return
+    fi
+  done <<< "$(supported_mcp_regions)"
+  false
+}
+
+run_mcp_fit_assessment() {
+  echo "Analyzing cluster configuration to determine optimal control plane..."
+
+  if ! is_supported_location; then
+    info "Cluster not in MCP-supported location."
+    false
+    return
+  fi
+  if is_private_cluster; then
+    info "Cluster has private API server endpoints enabled,"
+    false
+    return
+  fi
+  if is_autopilot; then
+    info "Cluster is a GKE Autopilot cluster."
+    false
+    return
+  fi
+
+  if [[ ! -f ./configuration_backup/default_iop ]]; then
+    istioctl profile dump empty >./configuration_backup/default_iop 2>/dev/null
+  fi
+
+  local ARGS; ARGS="-f ./configuration_backup/default_iop"
+  if [[ -f ./configuration_backup/iop_backup ]]; then
+    ARGS="-f ./configuration_backup/iop_backup"
+  fi
+
+  # shellcheck disable=SC2086
+  if ! istioctl asm mcp-migrate ${ARGS} > ./mcp_assess_out.log; then
+    info "Google recommends migrating your mesh to a Google-managed control plane."
+    info "However, the way your mesh is configured will change. Review the changes here:"
+
+    echo "**"
+    cat ./mcp_assess_out.log
+    echo "**"
+
+    info "If these are acceptable, enter Y to continue with installation of a Google-managed"
+    info "control plane. If you would like to continue to operate and maintain your own"
+    info "control plane, enter N to switch to an in-cluster control plane installation."
+
+    local response
+    read -rp "(Y/n)>" response
+
+    case "${response}" in
+      N* | n*)
+        touch ./configuration_backup/no_use_mcp
+        false
+        return
+        ;;
+    esac
+  fi
+
+  touch ./configuration_backup/use_mcp
 }
 
 main() {
@@ -1360,13 +1607,20 @@ main() {
     download_asm
     configure_kubectl
     pre_migrate
+    if should_use_mcp; then
+      info "Configuration verified for MCP."
+    fi
   fi
   if [[ "${INSTALL_ASM}" -eq 1 ]]; then
     ensure_backup
     configure_kubectl
     download_asm
     configure_package
-    install_asm
+    if should_use_mcp; then
+      install_mcp
+    else
+      install_asm
+    fi
   fi
   if [[ "${RELABEL}" -eq 1 ]]; then
     ensure_backup
