add usage and refactor create-mesh

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -133,111 +133,16 @@ main() {
 }
 create-mesh_subcommand() {
   ### Preparation ###
-  parse_cluster_args "$@"
-  prepare_add_to_mesh_environment
-  validate_cluster_args
+  parse_create_mesh_args "$@"
+  prepare_create_mesh_environment
+  validate_create_mesh_args
 
   ### Registration ###
-  add_all_to_mesh
+  create_mesh
   install_all_remote_secrets
 }
 
-parse_cluster_args() {
-  if [[ $# != 0 ]]; then
-    local FLEET_ID; FLEET_ID="${1}"
-    context_set-option "FLEET_ID" "${FLEET_ID}"
-    shift 1
-  fi
-
-  if [[ "${*}" = '' ]]; then
-    usage_short >&2
-    exit 2
-  fi
-
-  while [[ $# != 0 ]]; do
-    if [ -f "$1" ]; then
-      local KCF; KCF="${1}"
-      context_append "kubeconfigFiles" "${KCF}"
-    else
-      local CLUSTER; CLUSTER="${1}"
-      context_append "clustersInfo" "${CLUSTER//\// }"
-    fi
-    shift 1
-  done
-}
-
-validate_cluster_args() {
-  local KCF
-  local PROJECT_ID
-  local CLUSTER_LOCATION
-  local CLUSTER_NAME
-  local CTX_CLUSTER
-  local GKE_CLUSTER_URI
-
-  # validate fleet id is valid
-  get_project_number
-
-  # flatten any kubeconfig files into cluster P/L/C
-  # this is GCP-only and will need to be reworked for other platforms
-  while read -r KCF; do
-    # check a default context exists
-    local CONTEXT; CONTEXT="$(kubectl --kubeconfig "${KCF}" config current-context)"
-    if [[ -z "${CONTEXT}" ]]; then
-      fatal "Missing current-context in ${KCF}. Please set a current-context in the KUBECONFIG"
-    else
-      # use the default context to add to clusterInfo list
-      IFS="_" read -r _ PROJECT_ID CLUSTER_LOCATION CLUSTER_NAME <<EOF
-${CONTEXT}
-EOF
-      context_append "clustersInfo" "${PROJECT_ID} ${CLUSTER_LOCATION} ${CLUSTER_NAME}"
-    fi
-  done < <(context_list "kubeconfigFiles")
-
-  # validate clusters are valid
-  while read -r PROJECT_ID CLUSTER_LOCATION CLUSTER_NAME; do
-    context_set-option "PROJECT_ID" "${PROJECT_ID}"
-    context_set-option "CLUSTER_LOCATION" "${CLUSTER_LOCATION}"
-    context_set-option "CLUSTER_NAME" "${CLUSTER_NAME}"
-
-    validate_cluster
-    configure_kubectl
-
-    CTX_CLUSTER="$(kubectl config current-context)"
-    if ! is_membership_crd_installed; then
-      GKE_CLUSTER_URI="$(retry 2 gcloud container clusters describe "${CLUSTER_NAME}" \
-      --zone="${CLUSTER_LOCATION}" \
-      --project="${PROJECT_ID}" \
-      --format='value(selfLink)')"
-      context_append "clusterRegistrations" "${CTX_CLUSTER} ${GKE_CLUSTER_URI}"
-    else
-      exit_if_cluster_registered_to_another_fleet
-      warn "Cluster ${CLUSTER_NAME} is already registered with project ${PROJECT_ID}. Skipping."
-    fi
-    context_append "clusterContexts" "${CTX_CLUSTER}"
-  done <<EOF
-$(context_list "clustersInfo")
-EOF
-}
-
-exit_if_cluster_registered_to_another_fleet() {
-  local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
-  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
-  local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
-  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
-
-  local WANT
-  WANT="//container.googleapis.com/projects/${PROJECT_ID}/locations/${CLUSTER_LOCATION}/clusters/${CLUSTER_NAME}"
-  local LIST
-  LIST="$(gcloud container hub memberships list --project "${FLEET_ID}" \
-    --format=json | grep "${WANT}")"
-  if [[ -z "${LIST}" ]]; then
-    { read -r -d '' MSG; fatal "${MSG}"; } <<EOF || true
-Cluster is already registered but not in the project ${FLEET_ID}.
-EOF
-  fi
-}
-
-add_all_to_mesh() {
+create_mesh() {
   local CTX_CLUSTER GKE_CLUSTER_URI
 
   # for-loop does not read lines but words, so setting IFS to explicitly split with line breaks
@@ -294,38 +199,6 @@ install_one_remote_secret() {
     --context="${CTX_CLUSTER1}" \
     --name="${SECRET_NAME}" | \
     kubectl apply --context="${CTX_CLUSTER2}" -f -
-}
-
-# Need to prepare differently under multicluster environment
-# validate_cluster and configure_kubectl will be called in validation
-# for each cluster
-prepare_add_to_mesh_environment() {
-  set_up_local_workspace
-
-  validate_cli_dependencies
-
-  if is_sa; then
-    auth_service_account
-  fi
-
-  if needs_asm; then
-    if ! necessary_files_exist; then
-      download_asm
-    fi
-    organize_kpt_files
-  fi
-}
-
-generate_secret_name() {
-  local SECRET_NAME; SECRET_NAME="${1}"
-
-  if [[ "${#SECRET_NAME}" -gt "${KUBE_TAG_MAX_LEN}" ]]; then
-    local DIGEST
-    DIGEST="$(echo "${SECRET_NAME}" | sha256sum | head -c20 || true)"
-    SECRET_NAME="${SECRET_NAME:0:42}-${DIGEST}"
-  fi
-
-  echo "${SECRET_NAME}"
 }
 experimental_subcommand() {
   if [[ "${*}" = '' ]]; then
@@ -1049,6 +922,55 @@ FLAGS:
      --dry_run
      --only_validate
      --only_enable
+  -h|--help
+  --version
+EOF
+}
+
+create-mesh_usage() {
+  cat << EOF
+${SCRIPT_NAME} $(version_message)
+usage: ${SCRIPT_NAME} create-mesh FLEET_ID (PROJECT_ID/CLUSTER_LOCATION/CLUSTER_NAME | KUBECONFIG_PATH) ... 
+
+Create a service mesh using the GKE clusters provided by registering them to the fleet and install remote secrets on each
+pair of clusters.
+Cluster information and KUBECONFIG could be passed in interchangeably.
+You could pass in as many clusters as you want, as long as they are not already registered to other fleets.
+Clusters already registered to the specified fleet will be skipped, whereas those registered to other fleets will fail.
+
+FLAGS:
+  The following several flags are used to display help texts and the version message. 
+  -v|--verbose                        Print commands before and after execution.
+  -h|--help                           Show this message and exit.
+  --version                           Print the version of this tool and exit.
+
+EXAMPLE:
+The following invocation will create a mesh using the provided 6 clusters 
+by registering them to a fleet named "my_cluster" and install remote secrets on each pair of clusters:
+
+  $> ${SCRIPT_NAME} \\
+      create-mesh \\
+      my-fleet \\
+      my-project/us-central1-c/my-cluster1 \\
+      my-project/us-central1-c/my-cluster2 \\
+      my-project/us-central1-c/my-cluster3 \\
+      path/to/kubeconfig1 \\
+      path/to/kubeconfig2 \\ 
+      path/to/kubeconfig3 \\
+
+EOF
+}
+
+create-mesh_usage_short() {
+  cat << EOF
+${SCRIPT_NAME} $(version_message)
+usage: ${SCRIPT_NAME} create-mesh FLEET_ID (PROJECT_ID/CLUSTER_LOCATION/CLUSTER_NAME | KUBECONFIG_PATH) ... 
+
+Create a service mesh using the GKE clusters provided by registering them to the fleet.
+Use -h|--help with -v|--verbose to show detailed descriptions.
+
+FLAGS:
+  -v|--verbose
   -h|--help
   --version
 EOF
@@ -2523,6 +2445,18 @@ generate_membership_name() {
   echo "${MEMBERSHIP_NAME}"
 }
 
+generate_secret_name() {
+  local SECRET_NAME; SECRET_NAME="${1}"
+
+  if [[ "${#SECRET_NAME}" -gt "${KUBE_TAG_MAX_LEN}" ]]; then
+    local DIGEST
+    DIGEST="$(echo "${SECRET_NAME}" | sha256sum | head -c20 || true)"
+    SECRET_NAME="${SECRET_NAME:0:42}-${DIGEST}"
+  fi
+
+  echo "${SECRET_NAME}"
+}
+
 register_cluster() {
   if is_cluster_registered; then return; fi
 
@@ -2836,6 +2770,57 @@ parse_args() {
       usage
     else
       usage_short
+    fi
+    exit
+  fi
+}
+
+parse_create_mesh_args() {
+  if [[ $# -lt 2 ]]; then
+    create-mesh_usage_short
+    exit 2
+  fi
+
+  local FLEET_ID; FLEET_ID="${1}"
+  context_set-option "FLEET_ID" "${FLEET_ID}"
+  shift 1
+
+  while [[ $# != 0 ]]; do
+    case "${1}" in
+      -v | --verbose)
+        context_set-option "VERBOSE" 1
+        shift 1
+        ;;
+      -h | --help)
+        context_set-option "PRINT_HELP" 1
+        shift 1
+        ;;
+      --version)
+        context_set-option "PRINT_VERSION" 1
+        shift 1
+        ;;
+      *)
+        if [ -f "$1" ]; then
+          local KCF; KCF="${1}"
+          context_append "kubeconfigFiles" "${KCF}"
+        else
+          local CLUSTER; CLUSTER="${1}"
+          context_append "clustersInfo" "${CLUSTER//\// }"
+        fi
+        shift 1
+        ;;
+    esac
+  done
+  local PRINT_HELP; PRINT_HELP="$(context_get-option "PRINT_HELP")"
+  local PRINT_VERSION; PRINT_VERSION="$(context_get-option "PRINT_VERSION")"
+  local VERBOSE; VERBOSE="$(context_get-option "VERBOSE")"
+  if [[ "${PRINT_HELP}" -eq 1 || "${PRINT_VERSION}" -eq 1 ]]; then
+    if [[ "${PRINT_VERSION}" -eq 1 ]]; then
+      version_message
+    elif [[ "${VERBOSE}" -eq 1 ]]; then
+      create-mesh_usage
+    else
+      create-mesh_usage_short
     fi
     exit
   fi
@@ -3202,6 +3187,26 @@ prepare_environment() {
     download_kpt
   fi
   readonly AKPT
+
+  if needs_asm; then
+    if ! necessary_files_exist; then
+      download_asm
+    fi
+    organize_kpt_files
+  fi
+}
+
+# Need to prepare differently under multicluster environment
+# validate_cluster and configure_kubectl will be called in validation
+# for each cluster
+prepare_create_mesh_environment() {
+  set_up_local_workspace
+
+  validate_cli_dependencies
+
+  if is_sa; then
+    auth_service_account
+  fi
 
   if needs_asm; then
     if ! necessary_files_exist; then
@@ -3916,6 +3921,24 @@ EOF
   fi
 }
 
+exit_if_cluster_registered_to_another_fleet() {
+  local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
+  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
+  local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
+
+  local WANT
+  WANT="//container.googleapis.com/projects/${PROJECT_ID}/locations/${CLUSTER_LOCATION}/clusters/${CLUSTER_NAME}"
+  local LIST
+  LIST="$(gcloud container hub memberships list --project "${FLEET_ID}" \
+    --format=json | grep "${WANT}")"
+  if [[ -z "${LIST}" ]]; then
+    { read -r -d '' MSG; fatal "${MSG}"; } <<EOF || true
+Cluster is already registered but not in the project ${FLEET_ID}.
+EOF
+  fi
+}
+
 enable_workload_identity(){
   local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
   local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
@@ -4218,6 +4241,59 @@ arg_required() {
   if [[ ! "${2:-}" || "${2:0:1}" = '-' ]]; then
     fatal "Option ${1} requires an argument."
   fi
+}
+
+validate_create_mesh_args() {
+  local KCF
+  local PROJECT_ID
+  local CLUSTER_LOCATION
+  local CLUSTER_NAME
+  local CTX_CLUSTER
+  local GKE_CLUSTER_URI
+
+  # validate fleet id is valid
+  get_project_number
+
+  # flatten any kubeconfig files into cluster P/L/C
+  # this is GCP-only and will need to be reworked for other platforms
+  while read -r KCF; do
+    # check a default context exists
+    local CONTEXT; CONTEXT="$(kubectl --kubeconfig "${KCF}" config current-context)"
+    if [[ -z "${CONTEXT}" ]]; then
+      fatal "Missing current-context in ${KCF}. Please set a current-context in the KUBECONFIG"
+    else
+      # use the default context to add to clusterInfo list
+      IFS="_" read -r _ PROJECT_ID CLUSTER_LOCATION CLUSTER_NAME <<EOF
+${CONTEXT}
+EOF
+      context_append "clustersInfo" "${PROJECT_ID} ${CLUSTER_LOCATION} ${CLUSTER_NAME}"
+    fi
+  done < <(context_list "kubeconfigFiles")
+
+  # validate clusters are valid
+  while read -r PROJECT_ID CLUSTER_LOCATION CLUSTER_NAME; do
+    context_set-option "PROJECT_ID" "${PROJECT_ID}"
+    context_set-option "CLUSTER_LOCATION" "${CLUSTER_LOCATION}"
+    context_set-option "CLUSTER_NAME" "${CLUSTER_NAME}"
+
+    validate_cluster
+    configure_kubectl
+
+    CTX_CLUSTER="$(kubectl config current-context)"
+    if ! is_membership_crd_installed; then
+      GKE_CLUSTER_URI="$(retry 2 gcloud container clusters describe "${CLUSTER_NAME}" \
+      --zone="${CLUSTER_LOCATION}" \
+      --project="${PROJECT_ID}" \
+      --format='value(selfLink)')"
+      context_append "clusterRegistrations" "${CTX_CLUSTER} ${GKE_CLUSTER_URI}"
+    else
+      exit_if_cluster_registered_to_another_fleet
+      warn "Cluster ${CLUSTER_NAME} is already registered with project ${PROJECT_ID}. Skipping."
+    fi
+    context_append "clusterContexts" "${CTX_CLUSTER}"
+  done <<EOF
+$(context_list "clustersInfo")
+EOF
 }
 
 x_validate_install_args() {
