Consolidated cherry-picks from master branch
* Add timestamps if ts available and verbose mode (#621)

* Add warning for possible uninitialized meshconfig (#625)

* Change service account detection pattern (#631)

Use a more broad pattern for detecting if current gcloud account is a service account or not

* install_asm: allow setting GCLOUD_USER_OR_SA (#633)

Fixes #632

* Install istio-cni with securityContext for SELinux (#636)

* add samples directory with online-boutique manifests (#650)

* Add config for MCP CNI (#652)

* Add config for MCP CNI

This config was generated once, but isn't intended to be updated by repeating that generation process.

* Cherry-pick of 409f61cc6fc87a5897038a2a4e9f56657092f842

* Fix sed command to retrieve project id from workload identity (#662)

* Cherry-pick of d2802f45876bcf42cbfec1648ed971e604b07d59

* Adjust container commnad path for istio-cni-repair (#671)

Upstream has modified the template in 1.10.
https://github.com/istio/istio/pull/31906
This change is needed in order to use the new image in master branch
Scritaro. This change doesn't need to be cherry-picked to 1.9
since it's not affected.

* Move SA auth (#675)

* Handle when a user is using SA impersonation and allow roles/owners to satisfy cluster permissions check (#682)

* handle sa impersonation and users with owner role

Co-authored-by: Dan Le Febvre <dlf@google.com>

* Cherry-pick of b2a721f9297e4dd98c7d4c34e2759d817f251ee8

* Allow testing ASM package change in the same PR (#696)

* Allow testing ASM package change in the same PR

* remove curly brackets

* Allow testing ASM package change in the same PR for staging (#699)

* Cherry-pick of e15a6cbc04f0ae268bbf3b0aa443552404d32cfb

* Update retry() to show executed command when it failed (#714)

* Cherry-pick of 962f4abd8589b07e6a14d65488142c4c9612e2ec

* fix: option file for migrated meshca trustDomainAlias (#725)

* Add option to skip default gateway installation. (#765)

* Cherry-pick of 8d2085bca1042cc06e2257182526372138d528ca

* Copy asm from master

* Consolidated cherry-picks for kpt

* Ignore TZ in variable lint, fix other lints

* Fix overzealous sed

* Better readonly location

* Fix underzealous sed

* Fix missing file variable

* Consistency is important

* Move basic_suite to flaky tests

Co-authored-by: matthewkrupnik <60237964+matthewkrupnik@users.noreply.github.com>
Co-authored-by: Alexander Brand <alexbrand09@gmail.com>
Co-authored-by: Saverio Proto <zioproto@gmail.com>
Co-authored-by: cloud-pharaoh <aminamansour@gmail.com>
Co-authored-by: Michael Lopez <mickael.lopez@gmail.com>
Co-authored-by: Rui Gu <ruigu@google.com>
Co-authored-by: Dan <50656121+ddlfcloud@users.noreply.github.com>
Co-authored-by: Dan Le Febvre <dlf@google.com>
Co-authored-by: Jason Wang <jasonwzm@google.com>
Co-authored-by: kyasbal <kyasbal1994@gmail.com>
Co-authored-by: shankgan <69281265+shankgan@users.noreply.github.com>

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -51,6 +51,7 @@ OPERATOR_MANIFEST=""
 BETA_CRD_MANIFEST=""
 CITADEL_MANIFEST=""
 OFF_GCP_MANIFEST=""
+MANAGED_CNI=""
 MANAGED_MANIFEST=""
 MANAGED_WEBHOOKS=""
 EXPOSE_ISTIOD_SERVICE=""
@@ -66,7 +67,7 @@ SCRIPT_NAME="${0##*/}"; readonly SCRIPT_NAME
 PROJECT_NUMBER=""
 GKE_CLUSTER_URI=""
 GCE_NETWORK_NAME=""
-GCLOUD_USER_OR_SA=""
+GCLOUD_USER_OR_SA="${GCLOUD_USER_OR_SA:=}"
 KPT_URL=""
 KUBECONFIG=""
 APATH=""
@@ -125,13 +126,13 @@ main() {
 
 prepare_environment() {
   set_up_local_workspace
-  configure_kubectl
-
   validate_cli_dependencies
 
   if is_sa; then
     auth_service_account
   fi
+
+  configure_kubectl
 
   if should_validate || can_modify_at_all; then
     local_iam_user > /dev/null
@@ -139,6 +140,11 @@ prepare_environment() {
       validate_gcp_resources
     fi
   fi
+
+  if needs_asm && needs_kpt; then
+    download_kpt
+  fi
+  readonly AKPT
 
   if needs_asm; then
     if ! necessary_files_exist; then
@@ -187,6 +193,7 @@ init() {
   BETA_CRD_MANIFEST="${OPTIONS_DIRECTORY}/v1beta1-crds.yaml"; readonly BETA_CRD_MANIFEST;
   CITADEL_MANIFEST="${OPTIONS_DIRECTORY}/citadel-ca.yaml"; readonly CITADEL_MANIFEST;
   OFF_GCP_MANIFEST="${OPTIONS_DIRECTORY}/off-gcp.yaml"; readonly OFF_GCP_MANIFEST;
+  MANAGED_CNI="${OPTIONS_DIRECTORY}/cni-managed.yaml"; readonly MANAGED_CNI;
   MANAGED_MANIFEST="${OPTIONS_DIRECTORY}/managed-control-plane.yaml"; readonly MANAGED_MANIFEST;
   MANAGED_WEBHOOKS="${OPTIONS_DIRECTORY}/managed-control-plane-webhooks.yaml"; readonly MANAGED_WEBHOOKS;
   EXPOSE_ISTIOD_SERVICE="${PACKAGE_DIRECTORY}/expansion/expose-istiod.yaml"; readonly EXPOSE_ISTIOD_SERVICE;
@@ -202,7 +209,7 @@ init() {
 
   AKUBECTL="$(which kubectl || true)"; readonly AKUBECTL;
   AGCLOUD="$(which gcloud || true)"; readonly AGCLOUD;
-  AKPT="$(which kpt || true)"; readonly AKPT;
+  AKPT="$(which kpt || true)"
 }
 
 ### Convenience functions ###
@@ -284,6 +291,8 @@ retry() {
     warn "Failed, retrying...($((i+1)) of ${MAX_TRIES})"
     sleep 2
   done
+  local CMD="'$*'"
+  warn "Command $CMD failed."
   false
 }
 
@@ -370,7 +379,12 @@ error() {
 }
 
 info() {
-  echo "${SCRIPT_NAME}: ${1}" >&2
+  local VERBOSE; VERBOSE="$(context_get-option "VERBOSE")"
+  if hash ts 2>/dev/null && [[ "${VERBOSE}" -eq 1 ]]; then
+    echo "${SCRIPT_NAME}: ${1}" | TZ=utc ts '%Y-%m-%dT%.T' >&2
+  else
+    echo "${SCRIPT_NAME}: ${1}" >&2
+  fi
 }
 
 fatal() {
@@ -437,6 +451,11 @@ is_sa() {
   local SERVICE_ACCOUNT; SERVICE_ACCOUNT="$(context_get-option "SERVICE_ACCOUNT")"
 
   if [[ -z "${SERVICE_ACCOUNT}" ]]; then false; fi
+}
+
+is_sa_impersonation() {
+  local IMPERSONATE_USER; IMPERSONATE_USER="$(gcloud config get-value auth/impersonate_service_account)"
+  if [[ -z "${IMPERSONATE_USER}" ]]; then false; fi
 }
 
 should_validate() {
@@ -551,6 +570,24 @@ can_create_namespace() {
   fi
 }
 
+needs_kpt() {
+  if [[ -z "${AKPT}" ]]; then return; fi
+  local KPT_VER
+  KPT_VER="$(kpt version)"
+  if [[ "${KPT_VER:0:1}" != "0" ]]; then return; fi
+  false
+}
+
+add_trust_domain_alias() {
+  local TRUST_DOMAIN_ALIASES
+  TRUST_DOMAIN_ALIASES="$(context_get-option "TRUST_DOMAIN_ALIASES")"
+  if [[ "${TRUST_DOMAIN_ALIASES}" == *${1}* ]]; then
+    return
+  fi
+  TRUST_DOMAIN_ALIASES="${TRUST_DOMAIN_ALIASES} ${1}"
+  context_set-option "TRUST_DOMAIN_ALIASES" "${TRUST_DOMAIN_ALIASES}"
+}
+
 needs_asm() {
   local PRINT_CONFIG; PRINT_CONFIG="$(context_get-option "PRINT_CONFIG")"
 
@@ -634,6 +671,13 @@ parse_args() {
         ;;
       -o | --option)
         arg_required "${@}"
+
+        if [[ "${2}" == "cni-managed" ]]; then
+          context_set-option "USE_MCP_CNI" 1
+          shift 2
+          continue
+        fi
+
         OPTIONAL_OVERLAY="${2},${OPTIONAL_OVERLAY}"
         context_set-option "OPTIONAL_OVERLAY" "${OPTIONAL_OVERLAY}"
         if [[ "${2}" == "hub-meshca" ]]; then
@@ -1096,6 +1140,9 @@ set_up_local_workspace() {
       fatal "${OUTPUT_DIR} exists and is not a directory, please specify another directory."
     fi
   fi
+
+  if [[ -x "${OUTPUT_DIR}/kpt" ]]; then AKPT="$(apath -f "${OUTPUT_DIR}/kpt")"; fi
+
   pushd "$OUTPUT_DIR" > /dev/null
   context_set-option "OUTPUT_DIR" "${OUTPUT_DIR}"
 
@@ -1198,7 +1245,6 @@ $AGCLOUD
 grep
 jq
 $AKUBECTL
-$AKPT
 sed
 tr
 head
@@ -1212,7 +1258,6 @@ EOF
   done <<EOF
 AKUBECTL
 AGCLOUD
-AKPT
 EOF
 
   if [[ "${CUSTOM_CA}" -eq 1 ]]; then
@@ -1238,6 +1283,23 @@ EOF
   if [[ "$(uname -m)" != "x86_64" ]]; then
     fatal "Installation is only supported on x86_64."
   fi
+}
+
+download_kpt() {
+  local OS
+
+  case "$(uname)" in
+    Linux ) OS="linux_amd64";;
+    Darwin) OS="darwin_arm64";;
+    *     ) fatal "$(uname) is not a supported OS.";;
+  esac
+
+  local KPT_TGZ
+  KPT_TGZ="https://github.com/GoogleContainerTools/kpt/releases/download/v0.39.3/kpt_${OS}-0.39.3.tar.gz"
+
+  info "Downloading kpt.."
+  curl -L "${KPT_TGZ}" | tar xz
+  AKPT="$(apath -f kpt)"
 }
 
 download_asm() {
@@ -1637,12 +1699,11 @@ EOF
 
 exit_if_out_of_iam_policy() {
   local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
-  local GCLOUD_MEMBER; GCLOUD_MEMBER="$(iam_user)";
   local MEMBER_ROLES
   MEMBER_ROLES="$(gcloud projects \
     get-iam-policy "${PROJECT_ID}" \
     --flatten='bindings[].members' \
-    --filter="bindings.members:$(iam_user)" \
+    --filter="bindings.members:$(local_iam_user)" \
     --format='value(bindings.role)')"
 
   if [[ "${MEMBER_ROLES}" = *"roles/owner"* ]]; then
@@ -1667,16 +1728,6 @@ EOF
   fi
 }
 
-iam_user() {
-  local MANAGED_SERVICE_ACCOUNT; MANAGED_SERVICE_ACCOUNT="$(context_get-option "MANAGED_SERVICE_ACCOUNT")"
-  if ! is_managed; then
-    local_iam_user
-    return
-  fi
-
-  echo "serviceAccount:${MANAGED_SERVICE_ACCOUNT}"
-}
-
 local_iam_user() {
   if [[ -n "${GCLOUD_USER_OR_SA}" ]]; then
     echo "${GCLOUD_USER_OR_SA}"
@@ -1696,12 +1747,18 @@ local_iam_user() {
 
   local ACCOUNT_TYPE
   ACCOUNT_TYPE="user"
-  if is_sa || [[ "${ACCOUNT_NAME}" = *.iam.gserviceaccount.com ]]; then
+  if is_sa || [[ "${ACCOUNT_NAME}" = *.gserviceaccount.com ]]; then
     ACCOUNT_TYPE="serviceAccount"
   fi
 
-  GCLOUD_USER_OR_SA="${ACCOUNT_TYPE}:${ACCOUNT_NAME}"; readonly GCLOUD_USER_OR_SA
+  if is_sa_impersonation; then
+    ACCOUNT_NAME="$(gcloud config get-value auth/impersonate_service_account)"
+    ACCOUNT_TYPE="serviceAccount"
+    warn "Service account impersonation currently configured to impersonate '${ACCOUNT_NAME}'."
+  fi
 
+  GCLOUD_USER_OR_SA="${ACCOUNT_TYPE}:${ACCOUNT_NAME}"
+  readonly GCLOUD_USER_OR_SA
   echo "${GCLOUD_USER_OR_SA}"
 }
 
@@ -2043,7 +2100,7 @@ populate_fleet_info() {
   context_set-option "HUB_MEMBERSHIP_ID" "${HUB_MEMBERSHIP_ID}"
   HUB_IDP_URL="$(kubectl get memberships.hub.gke.io membership -o=jsonpath='{.spec.identity_provider}')"
   context_set-option "HUB_IDP_URL" "${HUB_IDP_URL}"
-  FLEET_ID="$(kubectl get memberships.hub.gke.io membership -o=json | jq .spec.workload_identity_pool | sed 's/^\"\(.*\).\(svc\|hub\).id.goog\"$/\1/g')"
+  FLEET_ID="$(kubectl get memberships.hub.gke.io membership -o=json | jq .spec.workload_identity_pool | sed -E 's/^\"(.*)\.(svc|hub)\.id\.goog\"$/\1/')"
   context_set-option "FLEET_ID" "${FLEET_ID}"
 }
 
@@ -2286,15 +2343,40 @@ configure_package() {
   fi
 
   if [[ "${USE_HUB_WIP}" -eq 1 ]]; then
-    kpt cfg set asm gcloud.project.environProjectID "${FLEET_ID}"
-    kpt cfg set asm anthos.servicemesh.hubMembershipID "${HUB_MEMBERSHIP_ID}"
-    kpt cfg set asm anthos.servicemesh.hub-idp-url "${HUB_IDP_URL}"
+    # VM installation uses the latest Hub WIP format
+    if [[ "${USE_VM}" -eq 1 ]]; then
+      kpt cfg set asm anthos.servicemesh.hubTrustDomain "${FLEET_ID}.svc.id.goog"
+      kpt cfg set asm anthos.servicemesh.hub-idp-url "${HUB_IDP_URL}"
+    # GKE-on-GCP installation uses legacy Hub WIP format to be consistent with GCP Hub public preview feature
+    else
+      kpt cfg set asm anthos.servicemesh.hubTrustDomain "${FLEET_ID}.hub.id.goog"
+      kpt cfg set asm anthos.servicemesh.hub-idp-url "https://gkehub.googleapis.com/projects/${FLEET_ID}/locations/global/memberships/${HUB_MEMBERSHIP_ID}"
+    fi
+  fi
+  if [[ -n "${CA_NAME}" && "${CA}" = "gcp_cas" ]]; then
+    kpt cfg set asm anthos.servicemesh.external_ca.ca_name "${CA_NAME}"
   fi
 
   if [[ "${USE_VM}" -eq 1 ]] && [[ "${_CI_NO_REVISION}" -eq 0 ]]; then
     kpt cfg set asm anthos.servicemesh.istiodHost "istiod-${REVISION_LABEL}.istio-system.svc"
     kpt cfg set asm anthos.servicemesh.istiodHostFQDN "istiod-${REVISION_LABEL}.istio-system.svc.cluster.local"
     kpt cfg set asm anthos.servicemesh.istiod-vs-name "istiod-vs-${REVISION_LABEL}"
+  fi
+
+  if [[ "${CA}" == "mesh_ca" ]]; then
+    # set the trust domain aliases to include both new Hub WIP and old Hub WIP to achieve no downtime upgrade.
+    add_trust_domain_alias "${PROJECT_ID}.svc.id.goog"
+    add_trust_domain_alias "${PROJECT_ID}.hub.id.goog"
+    if [[ -n "${_CI_TRUSTED_GCP_PROJECTS}" ]]; then
+      # Gather the trust domain aliases from projects.
+      while IFS=',' read -r trusted_gcp_project; do
+        add_trust_domain_alias "${trusted_gcp_project}.svc.id.goog"
+      done <<EOF
+${_CI_TRUSTED_GCP_PROJECTS}
+EOF
+    fi
+    # shellcheck disable=SC2046
+    kpt cfg set asm anthos.servicemesh.trustDomainAliases $(context_get-option "TRUST_DOMAIN_ALIASES")
   fi
 }
 create-mesh_subcommand() {
@@ -2767,6 +2849,37 @@ install_managed_components() {
   context_append "kubectlFiles" "${CR_CONTROL_PLANE_REVISION_REGULAR}"
   context_append "kubectlFiles" "${CR_CONTROL_PLANE_REVISION_RAPID}"
   context_append "kubectlFiles" "${CR_CONTROL_PLANE_REVISION_STABLE}"
+
+  local ASM_OPTS
+  ASM_OPTS="$(kubectl -n istio-system \
+    get --ignore-not-found cm asm-options \
+    -o jsonpath='{.data.ASM_OPTS}' || true)"
+
+  local USE_MCP_CNI; USE_MCP_CNI="$(context_get-option "USE_MCP_CNI")"
+  local CNI; CNI="off"
+  if [[ "${USE_MCP_CNI}" -eq 1 ]]; then
+    info "Configuring CNI..."
+    CNI="on"
+  fi
+
+  if [[ -z "${ASM_OPTS}" || "${ASM_OPTS}" != *"CNI=${CNI}"* ]]; then
+    cat >mcp_configmap.yaml <<EOF
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: asm-options
+  namespace: istio-system
+data:
+  ASM_OPTS: "CNI=${CNI}"
+EOF
+
+    context_append "kubectlFiles" "mcp_configmap.yaml"
+  fi
+
+  if [[ "${USE_MCP_CNI}" -eq 1 ]]; then
+    context_append "kubectlFiles" "${MANAGED_CNI}"
+  fi
 }
 
 scrape_managed_urls() {
@@ -2844,7 +2957,12 @@ install_private_ca() {
   # This sets up IAM privileges for the project to be able to access GCP CAS.
   # If modify_gcp_component permissions are not granted, it is assumed that the
   # user has taken care of this, else Istio setup will fail
-  local WORKLOAD_IDENTITY; WORKLOAD_IDENTITY="${WORKLOAD_POOL}[istio-system/istiod-service-account]"
+  local ISTIOD_SERVICE_ACCOUNT
+  ISTIOD_SERVICE_ACCOUNT="istiod-${REVISION_LABEL}"
+  if [[ "${_CI_NO_REVISION}" -eq 1 ]]; then
+    ISTIOD_SERVICE_ACCOUNT="istiod"
+  fi
+  local WORKLOAD_IDENTITY; WORKLOAD_IDENTITY="${WORKLOAD_POOL}[istio-system/${ISTIOD_SERVICE_ACCOUNT}]"
   local NAME; NAME=$(echo "${CA_NAME}" | cut -f6 -d/)
   local CA_LOCATION; CA_LOCATION=$(echo "${CA_NAME}" | cut -f4 -d/)
   local CA_PROJECT; CA_PROJECT=$(echo "${CA_NAME}" | cut -f2 -d/)
@@ -3213,14 +3331,23 @@ configure_private_ca() {
   kpt cfg set asm anthos.servicemesh.external_ca.ca_name "${CA_NAME}"
 }
 validate_in_cluster_control_plane() {
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
+  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
+
   if should_validate; then
     validate_environment
   fi
   if can_modify_gcp_components; then
     init_meshconfig
+  elif should_validate && [[ "${FLEET_ID}" == "${PROJECT_ID}" ]]; then
+    warn "There is no way to validate that the meshconfig API has been initialized."
+    warn "This needs to happen once per GCP project. If the API has not been initialized"
+    warn "for ${PROJECT_ID}, please re-run this tool with the --enable_gcp_components"
+    warn "flag. Otherwise, installation will succeed but Anthos Service Mesh"
+    warn_pause "will not function correctly."
   fi
   if can_modify_gcp_iam_roles; then
-    bind_user_to_iam_policy "$(required_iam_roles)" "$(iam_user)"
+    bind_user_to_iam_policy "$(required_iam_roles)" "$(local_iam_user)"
   elif should_validate; then
     exit_if_out_of_iam_policy
   fi
@@ -3263,13 +3390,9 @@ validate_managed_control_plane() {
     bind_user_to_iam_policy "roles/meshconfig.admin" "$(local_iam_user)"
   fi
   if can_modify_at_all; then
-    local MANAGED_SERVICE_JSON; MANAGED_SERVICE_JSON="$(init_meshconfig_managed)"
-    local MANAGED_SERVICE_ACCOUNT; MANAGED_SERVICE_ACCOUNT="$(echo "${MANAGED_SERVICE_JSON}" | jq -r .serviceAccount)"
-    if [[ -z "${MANAGED_SERVICE_JSON}" || "${MANAGED_SERVICE_ACCOUNT}" == "null" ]]; then
+    if ! init_meshconfig_managed; then
       fatal "Couldn't initialize meshconfig, do you have the required permission resourcemanager.projects.setIamPolicy?"
     fi
-    context_set-option "MANAGED_SERVICE_ACCOUNT" "${MANAGED_SERVICE_ACCOUNT}"
-    bind_user_to_iam_policy "$(required_iam_roles_mcp_sa)" "$(iam_user)"
   fi
 }
 
@@ -3353,9 +3476,11 @@ context_init() {
     "CUSTOM_CA": ${CUSTOM_CA:-0},
     "USE_HUB_WIP": ${USE_HUB_WIP:-0},
     "USE_VM": ${USE_VM:-0},
+    "USE_MCP_CNI": ${USE_MCP_CNI:-0},
     "FLEET_ID": "${FLEET_ID:-}",
     "HUB_MEMBERSHIP_ID": "${HUB_MEMBERSHIP_ID:-}",
     "CUSTOM_REVISION": ${CUSTOM_REVISION:-0},
+    "TRUST_DOMAIN_ALIASES": "${TRUST_DOMAIN_ALIASES:-}",
     "WI_ENABLED": ${WI_ENABLED:-0}
   },
   "istioctlFiles": [],
