Add support for multi cluster upgrade when FLEET WIP value is newly introduced as the trust domain (#955)
* Add support for multi project/trust domain upgrade

* add patch logic in create-mesh subcommand

* address comment

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -137,6 +137,7 @@ create-mesh_subcommand() {
 
   ### Registration ###
   create_mesh
+  patch_trust_domain_aliases
   install_all_remote_secrets
 }
 
@@ -162,6 +163,10 @@ create-mesh_parse_args() {
         ;;
       --version)
         context_set-option "PRINT_VERSION" 1
+        shift 1
+        ;;
+      --ignore_workload_identity_mismatch | --ignore-workload-identity-mismatch)
+        context_set-option "TRUST_FLEET_IDENTITY" 0
         shift 1
         ;;
       *)
@@ -320,6 +325,52 @@ create-mesh_prepare_environment() {
     fi
     organize_kpt_files
   fi
+}
+
+patch_trust_domain_aliases() {
+  local PROJECT_ID
+  local CLUSTER_LOCATION
+  local CLUSTER_NAME
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
+  local TRUST_FLEET_IDENTITY; TRUST_FLEET_IDENTITY="$(context_get-option "TRUST_FLEET_IDENTITY")"
+  if [[ "$TRUST_FLEET_IDENTITY" -eq 0 ]]; then
+    return
+  fi
+  while read -r PROJECT_ID CLUSTER_LOCATION CLUSTER_NAME; do
+    configure_kubectl "${PROJECT_ID}" "${CLUSTER_LOCATION}" "${CLUSTER_NAME}"
+    local ISTIOD_COUNT; ISTIOD_COUNT="$(get_istio_deployment_count)";
+    if [[ "$ISTIOD_COUNT" -ne 0 ]]; then
+      info "Check trust domain aliases of cluster gke_${PROJECT_ID}_${CLUSTER_LOCATION}_${CLUSTER_NAME}"
+      local REVISION; REVISION="$(retry 2 kubectl -n istio-system get pod -l istio=istiod \
+        -o jsonpath='{.items[].spec.containers[].env[?(@.name=="REVISION")].value}')"
+
+      # Patch the configmap of the cluster if it does not include FLEET_ID.svc.id.goog
+      if ! has_fleet_alias "${FLEET_ID}" "${REVISION}"; then
+        info "Patching istio-${REVISION} configmap trustDomainAliases on cluster ${PROJECT_ID}/${CLUSTER_LOCATION}/${CLUSTER_NAME} with ${FLEET_ID}.svc.id.goog"
+        local CONFIGMAP_YAML; CONFIGMAP_YAML="$(retry 2 kubectl -n istio-system get configmap istio-"${REVISION}" -o yaml)"
+        CONFIGMAP_YAML="$(echo "$CONFIGMAP_YAML" | sed '/^    trustDomainAliases:.*/a \    - '"${FLEET_ID}.svc.id.goog"'')"
+        echo "$CONFIGMAP_YAML"| kubectl apply -f - || warn "failed to patch the configmap istio-${REVISION}"
+      fi
+    fi
+
+  done <<EOF
+$(context_list "clustersInfo")
+EOF
+}
+
+has_fleet_alias() {
+  local FLEET_ID; FLEET_ID="${1}"
+  local REVISION; REVISION="${2}"
+  local RAW_TRUST_DOMAIN_ALIASES; RAW_TRUST_DOMAIN_ALIASES="$(retry 2 kubectl -n istio-system get configmap istio-"${REVISION}" \
+    -o jsonpath='{.data.mesh}' | sed -e '1,/trustDomainAliases:/ d')"
+  local RAW_TRUST_DOMAIN_ALIAS
+  while IFS= read -r RAW_TRUST_DOMAIN_ALIAS; do
+    if [[ "${RAW_TRUST_DOMAIN_ALIAS}" != *"- "* ]]; then false; return; fi
+    if [[ "${RAW_TRUST_DOMAIN_ALIAS}" == *"- ${FLEET_ID}.svc.id.goog"* ]]; then
+      return
+    fi
+  done < <(printf '%s\n' "$RAW_TRUST_DOMAIN_ALIASES")
+  false
 }
 experimental_subcommand() {
   if [[ "${*}" = '' ]]; then
@@ -1698,11 +1749,9 @@ validate_meshca() {
 }
 
 configure_meshca() {
-  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
   local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
   local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
   local USE_HUB_WIP; USE_HUB_WIP="$(context_get-option "USE_HUB_WIP")"
-  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   local HUB_MEMBERSHIP_ID; HUB_MEMBERSHIP_ID="$(context_get-option "HUB_MEMBERSHIP_ID")"
   local HUB_IDP_URL; HUB_IDP_URL="$(context_get-option "HUB_IDP_URL")"
 
@@ -1712,7 +1761,15 @@ configure_meshca() {
     kpt cfg set asm anthos.servicemesh.idp-url "https://container.googleapis.com/v1/projects/${PROJECT_ID}/locations/${CLUSTER_LOCATION}/clusters/${CLUSTER_NAME}"
   fi
 
-  # set the trust domain aliases to include both new Hub WIP and old Hub WIP to achieve no downtime upgrade.
+  configure_trust_domain_aliases
+}
+
+configure_trust_domain_aliases() {
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
+  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
+  local USE_HUB_WIP; USE_HUB_WIP="$(context_get-option "USE_HUB_WIP")"
+
+  # Set the trust domain aliases to include both new Hub WIP and old Hub WIP to achieve no downtime upgrade.
   add_trust_domain_alias "${FLEET_ID}.svc.id.goog"
   add_trust_domain_alias "${FLEET_ID}.hub.id.goog"
   if [[ "${FLEET_ID}" != "${PROJECT_ID}" ]]; then
@@ -1720,11 +1777,30 @@ configure_meshca() {
   fi
   if [[ -n "${_CI_TRUSTED_GCP_PROJECTS}" ]]; then
     # Gather the trust domain aliases from projects.
-    while IFS=',' read -r trusted_gcp_project; do
-      add_trust_domain_alias "${trusted_gcp_project}.svc.id.goog"
+    while IFS=',' read -ra TRUSTED_GCP_PROJECT_IDS; do
+      for trusted_gcp_project_id in "${TRUSTED_GCP_PROJECT_IDS[@]}"; do
+        add_trust_domain_alias "${trusted_gcp_project_id}.svc.id.goog"
+      done
     done <<EOF
 ${_CI_TRUSTED_GCP_PROJECTS}
 EOF
+  fi
+
+  local ISTIOD_COUNT; ISTIOD_COUNT="$(get_istio_deployment_count)";
+  # When it is the upgrade case, include the original trust domain aliases
+  if [[ "$ISTIOD_COUNT" -ne 0 ]]; then
+    local REVISION; REVISION="$(retry 2 kubectl -n istio-system get pod -l istio=istiod \
+      -o jsonpath='{.items[].spec.containers[].env[?(@.name=="REVISION")].value}')"
+    local RAW_TRUST_DOMAINS_ALIASES; RAW_TRUST_DOMAINS_ALIASES="$(retry 2 kubectl -n istio-system get configmap istio-"${REVISION}" \
+      -o jsonpath='{.data.mesh}' | sed -e '1,/trustDomainAliases:/ d')"
+    local RAW_TRUST_DOMAINS_ALIAS;
+    while IFS= read -r RAW_TRUST_DOMAINS_ALIAS; do
+      if [[ "$RAW_TRUST_DOMAINS_ALIAS" =~ "- " ]]; then
+        add_trust_domain_alias "${RAW_TRUST_DOMAINS_ALIAS//*- }"
+      else
+        break
+      fi
+    done < <(printf '%s\n' "$RAW_TRUST_DOMAINS_ALIASES")
   fi
 
   # shellcheck disable=SC2046
@@ -2426,6 +2502,7 @@ context_init() {
     "ENABLE_REGISTRATION": ${ENABLE_REGISTRATION:-0},
     "ENABLE_NAMESPACE_CREATION": ${ENABLE_NAMESPACE_CREATION:-0},
     "DISABLE_CANONICAL_SERVICE": ${DISABLE_CANONICAL_SERVICE:-0},
+    "TRUST_FLEET_IDENTITY": ${TRUST_FLEET_IDENTITY:-1},
     "PRINT_CONFIG": ${PRINT_CONFIG:-0},
     "NON_INTERACTIVE": ${NON_INTERACTIVE:-0},
     "SERVICE_ACCOUNT": "${SERVICE_ACCOUNT:-}",
