Fixing asmcli handling of default configmap

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -348,6 +348,16 @@ patch_trust_domain_aliases() {
   local CLUSTER_NAME
   local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   local TRUST_FLEET_IDENTITY; TRUST_FLEET_IDENTITY="$(context_get-option "TRUST_FLEET_IDENTITY")"
+  local CONFIGMAP;
+
+  # If the REVISION is currently empty or set to 'default', use the
+  # backward-compatible configmap name 'istio'; otherwise, use 'istio-${REVISION}'
+  if [[ "${REVISION:-default}" == "default" ]]; then {
+    CONFIGMAP="istio"
+  } else {
+    CONFIGMAP="istio-${REVISION}"
+  }
+
   if [[ "$TRUST_FLEET_IDENTITY" -eq 0 ]]; then
     return
   fi
@@ -375,10 +385,10 @@ patch_trust_domain_aliases() {
 
       # Patch the configmap of the cluster if it does not include FLEET_ID.svc.id.goog
       if ! has_fleet_alias "${FLEET_ID}" "${REVISION}"; then
-        info "Patching istio-${REVISION} configmap trustDomainAliases on cluster ${PROJECT_ID}/${CLUSTER_LOCATION}/${CLUSTER_NAME} with ${FLEET_ID}.svc.id.goog"
-        local CONFIGMAP_YAML; CONFIGMAP_YAML="$(retry 2 kubectl -n istio-system get configmap istio-"${REVISION}" -o yaml)"
+        info "Patching ${CONFIGMAP} configmap trustDomainAliases on cluster ${PROJECT_ID}/${CLUSTER_LOCATION}/${CLUSTER_NAME} with ${FLEET_ID}.svc.id.goog"
+        local CONFIGMAP_YAML; CONFIGMAP_YAML="$(retry 2 kubectl -n istio-system get configmap "${CONFIGMAP} -o yaml)"
         CONFIGMAP_YAML="$(echo "$CONFIGMAP_YAML" | sed '/^    trustDomainAliases:.*/a \    - '"${FLEET_ID}.svc.id.goog"'')"
-        echo "$CONFIGMAP_YAML"| kubectl apply -f - || warn "failed to patch the configmap istio-${REVISION}"
+        echo "$CONFIGMAP_YAML"| kubectl apply -f - || warn "failed to patch the configmap ${CONFIGMAP}"
       fi
     fi
 
@@ -390,7 +400,17 @@ EOF
 has_fleet_alias() {
   local FLEET_ID; FLEET_ID="${1}"
   local REVISION; REVISION="${2}"
-  local RAW_TRUST_DOMAIN_ALIASES; RAW_TRUST_DOMAIN_ALIASES="$(retry 2 kubectl -n istio-system get configmap istio-"${REVISION}" \
+  local CONFIGMAP;
+
+  # If the REVISION is currently empty or set to 'default', use the
+  # backward-compatible configmap name 'istio'; otherwise, use 'istio-${REVISION}'
+  if [[ "${REVISION:-default}" == "default" ]]; then {
+    CONFIGMAP="istio"
+  } else {
+    CONFIGMAP="istio-${REVISION}"
+  }
+
+  local RAW_TRUST_DOMAIN_ALIASES; RAW_TRUST_DOMAIN_ALIASES="$(retry 2 kubectl -n istio-system get configmap "${CONFIGMAP}" \
     -o jsonpath='{.data.mesh}' | sed -e '1,/trustDomainAliases:/ d')"
   local RAW_TRUST_DOMAIN_ALIAS
   while IFS= read -r RAW_TRUST_DOMAIN_ALIAS; do
@@ -1832,12 +1852,22 @@ ${_CI_TRUSTED_GCP_PROJECTS}
 EOF
   fi
 
+  local CONFIGMAP;
+
+  # If the REVISION is currently empty or set to 'default', use the
+  # backward-compatible configmap name 'istio'; otherwise, use 'istio-${REVISION}'
+  if [[ "${REVISION:-default}" == "default" ]]; then {
+    CONFIGMAP="istio"
+  } else {
+    CONFIGMAP="istio-${REVISION}"
+  }
+
   local ISTIOD_COUNT; ISTIOD_COUNT="$(get_istio_deployment_count)";
   # When it is the upgrade case, include the original trust domain aliases
   if [[ "$ISTIOD_COUNT" -ne 0 ]]; then
     local REVISION; REVISION="$(retry 2 kubectl -n istio-system get pod -l app=istiod \
       -o jsonpath='{.items[].spec.containers[].env[?(@.name=="REVISION")].value}')"
-    local RAW_TRUST_DOMAINS_ALIASES; RAW_TRUST_DOMAINS_ALIASES="$(retry 2 kubectl -n istio-system get configmap istio-"${REVISION}" \
+    local RAW_TRUST_DOMAINS_ALIASES; RAW_TRUST_DOMAINS_ALIASES="$(retry 2 kubectl -n istio-system get configmap "${CONFIGMAP}" \
       -o jsonpath='{.data.mesh}' | sed -e '1,/trustDomainAliases:/ d')"
     local RAW_TRUST_DOMAINS_ALIAS;
     while IFS= read -r RAW_TRUST_DOMAINS_ALIAS; do
