rename add-to-mesh subcommand (#767)
* rename add-to-mesh subcommand

* use hash instead of rand

* address comments

* delete test from main

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -113,9 +113,9 @@ main() {
       shift 1
       print-config_subcommand "${@}"
       ;;
-    add-to-mesh)
+    create-mesh)
       shift 1
-      add-to-mesh_subcommand "${@}"
+      create-mesh_subcommand "${@}"
       ;;
     *)
       help_subcommand "${@}"
@@ -1946,7 +1946,7 @@ generate_membership_name() {
     --project "${PROJECT_ID}" | grep -c "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
       MEMBERSHIP_NAME="${CLUSTER_NAME}-${PROJECT_ID}-${CLUSTER_LOCATION}"
     fi
-    if [[ "${#MEMBERSHIP_NAME}" -gt 63 ]] || [[ "$(retry 2 gcloud container hub \
+    if [[ "${#MEMBERSHIP_NAME}" -gt "${KUBE_TAG_MAX_LEN}" ]] || [[ "$(retry 2 gcloud container hub \
     memberships list --format='value(name)' --project "${PROJECT_ID}" | grep -c \
     "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
       local RAND
@@ -2301,7 +2301,7 @@ configure_package() {
     kpt cfg set asm anthos.servicemesh.istiod-vs-name "istiod-vs-${REVISION_LABEL}"
   fi
 }
-add-to-mesh_subcommand() {
+create-mesh_subcommand() {
   ### Preparation ###
   parse_cluster_args "$@"
   prepare_add_to_mesh_environment
@@ -2428,7 +2428,7 @@ EOF
 install_one_remote_secret() {
   local CTX_CLUSTER1; CTX_CLUSTER1="${1}"
   local CTX_CLUSTER2; CTX_CLUSTER2="${2}"
-  local SECRET_NAME; SECRET_NAME="${CTX_CLUSTER1//_/-}"
+  local SECRET_NAME; SECRET_NAME="$(generate_secret_name "${CTX_CLUSTER1//_/-}")"
 
   info "Installing remote secret ${SECRET_NAME} on ${CTX_CLUSTER2}..."
 
@@ -2456,6 +2456,18 @@ prepare_add_to_mesh_environment() {
     fi
     organize_kpt_files
   fi
+}
+
+generate_secret_name() {
+  local SECRET_NAME; SECRET_NAME="${1}"
+
+  if [[ "${#SECRET_NAME}" -gt "${KUBE_TAG_MAX_LEN}" ]]; then
+    local DIGEST
+    DIGEST="$(echo "${SECRET_NAME}" | sha256sum | head -c20 || true)"
+    SECRET_NAME="${SECRET_NAME:0:42}-${DIGEST}"
+  fi
+
+  echo "${SECRET_NAME}"
 }
 help_subcommand() {
   local PRINT_HELP; PRINT_HELP=0
@@ -2516,7 +2528,7 @@ SUBCOMMANDS:
   install                             Install will attempt a new ASM installation
   validate                            Validate will attempt a new ASM validation
   print-config                        Print Config will attempt to print the configurations used
-  add-to-mesh                         Add multiple clusters to the mesh
+  create-mesh                         Add multiple clusters to the mesh
 
 OPTIONS:
   -l|--cluster_location  <LOCATION>   The GCP location of the target cluster.
@@ -2661,7 +2673,7 @@ SUBCOMMANDS:
   install
   validate
   print-config
-  add-to-mesh
+  create-mesh
 
 OPTIONS:
   -l|--cluster_location  <LOCATION>
@@ -3393,6 +3405,8 @@ context_list() {
   local KEY; KEY="${1}"
   jq -S -r --arg KEY "${KEY}" '.[$KEY][]' "${context_FILE_LOCATION}"
 }
+KUBE_TAG_MAX_LEN=63; readonly KUBE_TAG_MAX_LEN
+
 gen_install_params() {
   local CA; CA="$(context_get-option "CA")"
 
