Migrate to managed csc controller

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -1224,6 +1224,17 @@ install_canonical_controller() {
   info "...done!"
 }
 
+install_managed_canonical_controller() {
+  local IN_CLUSTER_CSC_DEP="$(kubectl get deployment/canonical-service-controller-manager -n asm-system --ignore-not-found=true || true)"
+  if [[ -z "$IN_CLUSTER_CSC_DEP" ]]; then
+    # In-cluster canonical service controller present
+    warn "Kindly migrate to managed canonical service controller. Refer <Doc>"
+  else
+    enable_service_mesh_feature
+    check_managed_canonical_controller_state
+  fi
+}
+
 install_fleet_api() {
   local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
   local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
@@ -1389,9 +1400,7 @@ install_control_plane() {
     if use_fleet_api; then install_fleet_api; else install_control_plane_revision; fi
   fi
 
-  if [[ "$DISABLE_CANONICAL_SERVICE" -eq 0 ]] && ! is_managed; then
-    install_canonical_controller
-  fi
+  install_managed_canonical_controller
 }
 validate_subcommand() {
   ### Preparation ###
@@ -4705,6 +4714,43 @@ get_monitoring_config_membership_json () {
   CONFIG="$(gcloud container hub memberships describe "${MEMBERSHIP_NAME}" --project "${PROJECT_ID}" --format="json(monitoringConfig)")"
   echo "${CONFIG}"
 }
+
+check_managed_canonical_controller_state() {
+  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
+  local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
+  local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
+  local MEMBERSHIP_NAME; MEMBERSHIP_NAME="$(generate_membership_name "${PROJECT_ID}" "${CLUSTER_LOCATION}" "${CLUSTER_NAME}")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
+
+  local CSC_STATUS_AVAILABLE=0
+  local CS_ERROR="CANONICAL_SERVICE_ERROR"
+  local MEMBERSHIP_STATE,CODE, CONDITIONS
+
+  for i in {1..3}; do
+    MEMBERSHIP_STATE=$( gcloud container fleet mesh describe --project "${FLEET_ID}" --format=json | \
+                     	jq '.membershipStates | with_entries(select(.key|test("'"${MEMBERSHIP_NAME}"'")))[]' )
+    CODE=$( jq -r '.state.code' <<< "$MEMBERSHIP_STATE" )
+    if [ "$CODE" = "OK" ]; then
+      info "Managed Canonical Service Controller working successfully"
+      CSC_STATUS_AVAILABLE=1; break
+    elif [ "$CODE" = "WARNING" ]; then
+      CONDITIONS=$( jq -r '.servicemesh.conditions'  <<< "$MEMBERSHIP_STATE" )
+      if grep -q "$CS_ERROR" <<< "$CONDITIONS"; then
+        warn "Managed Canonical Service Controller facing issues. Kindly refer to <wiki link>"
+        CSC_STATUS_AVAILABLE=1
+      fi
+      break
+    else
+      echo "Retry to get featureState.code for the membership: $MEMBERSHIP_NAME"
+      sleep 3
+    fi
+  done
+
+  if [ ${CSC_STATUS_AVAILABLE} -eq 0 ]; then
+    warn "Unable to verify Managed Canonical Service Controller State. Kindly refer to <wiki link>"
+  fi
+}
+
 validate_revision_label() {
   # Matches DNS label formats of RFC 1123
   local DNS_1123_LABEL_MAX_LEN; DNS_1123_LABEL_MAX_LEN=63;
