Add experimental mcp-migrate-check

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -335,6 +335,10 @@ experimental_subcommand() {
       shift 1
       x_install_subcommand "${@}"
       ;;
+    mcp-migrate-check)
+      shift 1
+      x_mcp_migrate_check "${@}"
+      ;;
     *)
       x_help_subcommand "${@}"
       ;;
@@ -357,6 +361,10 @@ SUBCOMMANDS:
                                       instead of client-side tools
   vm                                  Functions to configure a mesh to
                                       allow external VM workloads.
+  mcp-migrate-check                   Checks IstioOperator config for
+                                      compatibility with a Google managed
+                                      control plane and generates new config
+                                      where possible.
 EOF
 }
 x_install_subcommand() {
@@ -394,6 +402,66 @@ x_configure_package() {
   if [[ -n "${_CI_ASM_IMAGE_TAG}" ]]; then
     kpt cfg set asm anthos.servicemesh.tag "${_CI_ASM_IMAGE_TAG}"
   fi
+}
+x_mcp_migrate_check() {
+  x_parse_mcp_migrate_args "${@}"
+  x_download_istioctl_tarball
+  context_set-option "VERBOSE" 1
+
+  PARAMS=""
+  for yaml_file in $(context_list "istioctlFiles"); do
+    PARAMS="${PARAMS} -f ${yaml_file}"
+  done
+
+  # shellcheck disable=SC2086
+  x_istioctl asm mcp-migrate ${PARAMS}
+}
+
+x_parse_mcp_migrate_args() {
+  # shellcheck disable=SC2064
+  trap "$(shopt -p nocasematch)" RETURN
+  shopt -s nocasematch
+
+  while [[ $# != 0 ]]; do
+    case "${1}" in
+      -f)
+        arg_required "${@}"
+        if [[ ! -f "${2}" ]]; then
+          fatal "Couldn't find yaml file ${2}."
+        fi
+        context_append "istioctlFiles" "${2}"
+        shift 2
+        ;;
+      *)
+        fatal "Unknown option ${1}"
+        ;;
+    esac
+  done
+}
+
+x_download_istioctl_tarball() {
+  case "$(uname)" in
+    Linux ) OS="linux-amd64";;
+    Darwin) OS="osx";;
+    *     ) fatal "$(uname) is not a supported OS.";;
+  esac
+
+  info "Downloading ASM.."
+  local TARBALL; TARBALL="istio-${RELEASE}-${OS}.tar.gz"
+  if [[ -z "${_CI_ASM_PKG_LOCATION}" ]]; then
+    curl -L "https://storage.googleapis.com/gke-release/asm/${TARBALL}" \
+      | tar xz
+  else
+    local TOKEN; TOKEN="$(retry 2 gcloud auth print-access-token)"
+    run_command curl -L "https://storage.googleapis.com/${_CI_ASM_PKG_LOCATION}/asm/${TARBALL}" \
+      --header @- <<EOF | tar xz
+Authorization: Bearer ${TOKEN}
+EOF
+  fi
+}
+
+x_istioctl() {
+  run_command "$(istioctl_path)" "${@}"
 }
 x_validate_dependencies() {
   local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
