transform cli tests to unit tests (#745)

diff --git a/asmcli/asmcli b/asmcli/asmcli
--- a/asmcli/asmcli
+++ b/asmcli/asmcli
@@ -27,7 +27,6 @@ _CI_NO_VALIDATE="${_CI_NO_VALIDATE:=0}"; readonly _CI_NO_VALIDATE;
 _CI_NO_REVISION="${_CI_NO_REVISION:=0}"; readonly _CI_NO_REVISION;
 _CI_ISTIOCTL_REL_PATH="${_CI_ISTIOCTL_REL_PATH:=}"; readonly _CI_ISTIOCTL_REL_PATH;
 _CI_TRUSTED_GCP_PROJECTS="${_CI_TRUSTED_GCP_PROJECTS:=}"; readonly _CI_TRUSTED_GCP_PROJECTS;
-_CI_ENVIRON_PROJECT_NUMBER="${_CI_ENVIRON_PROJECT_NUMBER:=}"; readonly _CI_ENVIRON_PROJECT_NUMBER;
 _CI_CRC_VERSION="${_CI_CRC_VERSION:=0}"; readonly _CI_CRC_VERSION;
 _CI_I_AM_A_TEST_ROBOT="${_CI_I_AM_A_TEST_ROBOT:=0}"; readonly _CI_I_AM_A_TEST_ROBOT;
 
@@ -594,6 +593,11 @@ parse_args() {
         warn "As of version 1.10 the --mode flag is deprecated and will be ignored."
         shift 2
         ;;
+      --fleet_id | --fleet-id)
+        arg_required "${@}"
+        context_set-option "FLEET_ID" "${2}"
+        shift 2
+        ;;
       -c | --ca)
         arg_required "${@}"
         context_set-option "CA" "$(echo "${2}" | tr '[:upper:]' '[:lower:]')"
@@ -769,6 +773,7 @@ validate_args() {
   local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
   local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
   local PLATFORM; PLATFORM="$(context_get-option "PLATFORM")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   local CA; CA="$(context_get-option "CA")"
   local CUSTOM_OVERLAY; CUSTOM_OVERLAY="$(context_get-option "CUSTOM_OVERLAY")"
   local OPTIONAL_OVERLAY; OPTIONAL_OVERLAY="$(context_get-option "OPTIONAL_OVERLAY")"
@@ -800,7 +805,6 @@ validate_args() {
   local CUSTOM_CA; CUSTOM_CA="$(context_get-option "CUSTOM_CA")"
   local USE_HUB_WIP; USE_HUB_WIP="$(context_get-option "USE_HUB_WIP")"
   local USE_VM; USE_VM="$(context_get-option "USE_VM")"
-  local ENVIRON_PROJECT_ID; ENVIRON_PROJECT_ID="$(context_get-option "ENVIRON_PROJECT_ID")"
   local HUB_MEMBERSHIP_ID; HUB_MEMBERSHIP_ID="$(context_get-option "HUB_MEMBERSHIP_ID")"
   local CUSTOM_REVISION; CUSTOM_REVISION="$(context_get-option "CUSTOM_REVISION")"
   local WI_ENABLED; WI_ENABLED="$(context_get-option "WI_ENABLED")"
@@ -908,9 +912,15 @@ EOF
     fi
   fi
 
-  if can_register_cluster && ! has_value "ENVIRON_PROJECT_ID"; then
+  # GCP only: when no Fleet Id is provided, default to the cluster's project as the Fleet host.
+  if [[ -z "${FLEET_ID}" ]] && is_gcp; then
+    FLEET_ID="${PROJECT_ID}"
+    context_set-option "FLEET_ID" "${FLEET_ID}"
+  fi
+
+  if can_register_cluster && ! has_value "FLEET_ID"; then
     MISSING_ARGS=1
-    warn "Missing ENVIRON_PROJECT_ID to register the cluster."
+    warn "Missing FLEET_ID to register the cluster."
   fi
 
   if [[ "${MISSING_ARGS}" -ne 0 ]]; then
@@ -1280,17 +1290,19 @@ EOF
   fi
 }
 
+# For GCP: project number corresponds to the (optional) ASM Fleet project or the (default) cluster's project.
+# For non-GCP: project number corresponds to the (required) ASM Fleet project.
 get_project_number() {
-  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   local RESULT; RESULT=""
 
-  info "Checking for project ${PROJECT_ID}..."
+  info "Checking for project ${FLEET_ID}..."
 
-  PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format="value(projectNumber)")"; readonly PROJECT_NUMBER
+  PROJECT_NUMBER="$(gcloud projects describe "${FLEET_ID}" --format="value(projectNumber)")"; readonly PROJECT_NUMBER
 
   if [[ -z "${PROJECT_NUMBER}" ]]; then
     { read -r -d '' MSG; fatal "${MSG}"; } <<EOF || true
-Unable to find project ${PROJECT_ID}. Please verify the spelling and try
+Unable to find project ${FLEET_ID}. Please verify the spelling and try
 again. To see a list of your projects, run:
   gcloud projects list --format='value(project_id)'
 EOF
@@ -1866,42 +1878,46 @@ is_cluster_registered() {
     false
   fi
 
-  populate_environ_info
+  populate_fleet_info
   local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
   local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
   local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
-  local ENVIRON_PROJECT_ID; ENVIRON_PROJECT_ID="$(context_get-option "ENVIRON_PROJECT_ID")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
 
   local WANT
   WANT="//container.googleapis.com/projects/${PROJECT_ID}/locations/${CLUSTER_LOCATION}/clusters/${CLUSTER_NAME}"
   local LIST
-  LIST="$(gcloud container hub memberships list --project "${ENVIRON_PROJECT_ID}" \
+  LIST="$(gcloud container hub memberships list --project "${FLEET_ID}" \
     --format=json | grep "${WANT}")"
   if [[ -z "${LIST}" ]]; then
     { read -r -d '' MSG; warn "${MSG}"; } <<EOF || true
-Cluster is registered in the project ${ENVIRON_PROJECT_ID}, but the script is
+Cluster is registered in the project ${FLEET_ID}, but the script is
 unable to verify in the project. The script will continue to execute.
 EOF
   fi
 }
 
 generate_membership_name() {
-  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
-  local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
-  local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
+  if is_gcp; then
+    local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
+    local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
+    local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
 
-  local MEMBERSHIP_NAME
-  MEMBERSHIP_NAME="${CLUSTER_NAME}"
-  if [[ "$(retry 2 gcloud container hub memberships list --format='value(name)' \
-   --project "${PROJECT_ID}" | grep -c "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
-    MEMBERSHIP_NAME="${CLUSTER_NAME}-${PROJECT_ID}-${CLUSTER_LOCATION}"
-  fi
-  if [[ "${#MEMBERSHIP_NAME}" -gt 63 ]] || [[ "$(retry 2 gcloud container hub \
-   memberships list --format='value(name)' --project "${PROJECT_ID}" | grep -c \
-   "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
-    local RAND
-    RAND="$(tr -dc "a-z0-9" </dev/urandom | head -c8 || true)"
-    MEMBERSHIP_NAME="${CLUSTER_NAME:0:54}-${RAND}"
+    local MEMBERSHIP_NAME
+    MEMBERSHIP_NAME="${CLUSTER_NAME}"
+    if [[ "$(retry 2 gcloud container hub memberships list --format='value(name)' \
+    --project "${PROJECT_ID}" | grep -c "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
+      MEMBERSHIP_NAME="${CLUSTER_NAME}-${PROJECT_ID}-${CLUSTER_LOCATION}"
+    fi
+    if [[ "${#MEMBERSHIP_NAME}" -gt 63 ]] || [[ "$(retry 2 gcloud container hub \
+    memberships list --format='value(name)' --project "${PROJECT_ID}" | grep -c \
+    "^${MEMBERSHIP_NAME}$" || true)" -ne 0 ]]; then
+      local RAND
+      RAND="$(tr -dc "a-z0-9" </dev/urandom | head -c8 || true)"
+      MEMBERSHIP_NAME="${CLUSTER_NAME:0:54}-${RAND}"
+    fi
+  else
+    MEMBERSHIP_NAME="$(date +%s%N)"
   fi
   echo "${MEMBERSHIP_NAME}"
 }
@@ -1920,9 +1936,9 @@ register_cluster() {
   MEMBERSHIP_NAME="$(generate_membership_name)"
   info "Registering the cluster as ${MEMBERSHIP_NAME}..."
 
-  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   retry 2 gcloud beta container hub memberships register "${MEMBERSHIP_NAME}" \
-    --project="${PROJECT_ID}" \
+    --project="${FLEET_ID}" \
     --gke-uri="${GKE_CLUSTER_URI}" \
     --enable-workload-identity
 }
@@ -1973,12 +1989,12 @@ is_membership_crd_installed() {
   fi
 }
 
-populate_environ_info() {
-  local ENVIRON_PROJECT_ID; ENVIRON_PROJECT_ID="$(context_get-option "ENVIRON_PROJECT_ID")"
+populate_fleet_info() {
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   local HUB_MEMBERSHIP_ID; HUB_MEMBERSHIP_ID="$(context_get-option "HUB_MEMBERSHIP_ID")"
   local HUB_IDP_URL; HUB_IDP_URL="$(context_get-option "HUB_IDP_URL")"
 
-  if [[ -n "${ENVIRON_PROJECT_ID}" && \
+  if [[ -n "${FLEET_ID}" && \
     -n "${HUB_MEMBERSHIP_ID}" && \
     -n "${HUB_IDP_URL}" ]]; then return; fi
 
@@ -1987,8 +2003,8 @@ populate_environ_info() {
   context_set-option "HUB_MEMBERSHIP_ID" "${HUB_MEMBERSHIP_ID}"
   HUB_IDP_URL="$(kubectl get memberships.hub.gke.io membership -o=jsonpath='{.spec.identity_provider}')"
   context_set-option "HUB_IDP_URL" "${HUB_IDP_URL}"
-  ENVIRON_PROJECT_ID="$(kubectl get memberships.hub.gke.io membership -o=json | jq .spec.workload_identity_pool | sed 's/^\"\(.*\).\(svc\|hub\).id.goog\"$/\1/g')"
-  context_set-option "ENVIRON_PROJECT_ID" "${ENVIRON_PROJECT_ID}"
+  FLEET_ID="$(kubectl get memberships.hub.gke.io membership -o=json | jq .spec.workload_identity_pool | sed 's/^\"\(.*\).\(svc\|hub\).id.goog\"$/\1/g')"
+  context_set-option "FLEET_ID" "${FLEET_ID}"
 }
 
 enable_workload_identity(){
@@ -2194,7 +2210,7 @@ configure_package() {
   local CLUSTER_NAME; CLUSTER_NAME="$(context_get-option "CLUSTER_NAME")"
   local CLUSTER_LOCATION; CLUSTER_LOCATION="$(context_get-option "CLUSTER_LOCATION")"
   local USE_HUB_WIP; USE_HUB_WIP="$(context_get-option "USE_HUB_WIP")"
-  local ENVIRON_PROJECT_ID; ENVIRON_PROJECT_ID="$(context_get-option "ENVIRON_PROJECT_ID")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   local HUB_MEMBERSHIP_ID; HUB_MEMBERSHIP_ID="$(context_get-option "HUB_MEMBERSHIP_ID")"
   local CA; CA="$(context_get-option "CA")"
   local CA_NAME; CA_NAME="$(context_get-option "CA_NAME")"
@@ -2205,13 +2221,10 @@ configure_package() {
   info "Configuring kpt package..."
 
   populate_cluster_values
-  populate_environ_info
+  populate_fleet_info
   kpt cfg set asm gcloud.container.cluster "${CLUSTER_NAME}"
   kpt cfg set asm gcloud.core.project "${PROJECT_ID}"
   kpt cfg set asm gcloud.project.environProjectNumber "${PROJECT_NUMBER}"
-  if [[ -n "${_CI_ENVIRON_PROJECT_NUMBER}" ]]; then
-    kpt cfg set asm gcloud.project.environProjectNumber "${_CI_ENVIRON_PROJECT_NUMBER}"
-  fi
   kpt cfg set asm gcloud.compute.location "${CLUSTER_LOCATION}"
   kpt cfg set asm gcloud.compute.network "${GCE_NETWORK_NAME}"
   kpt cfg set asm anthos.servicemesh.rev "${REVISION_LABEL}"
@@ -2224,7 +2237,7 @@ configure_package() {
   fi
 
   if [[ "${USE_HUB_WIP}" -eq 1 ]]; then
-    kpt cfg set asm gcloud.project.environProjectID "${ENVIRON_PROJECT_ID}"
+    kpt cfg set asm gcloud.project.environProjectID "${FLEET_ID}"
     kpt cfg set asm anthos.servicemesh.hubMembershipID "${HUB_MEMBERSHIP_ID}"
     kpt cfg set asm anthos.servicemesh.hub-idp-url "${HUB_IDP_URL}"
   fi
@@ -2299,11 +2312,14 @@ OPTIONS:
   -l|--cluster_location  <LOCATION>   The GCP location of the target cluster.
   -n|--cluster_name      <NAME>       The name of the target cluster.
   -p|--project_id        <ID>         The GCP project ID.
-  --kc|--kubeconfig      <KUBECONFIG> Path to the kubeconfig file to use for CLI requests.
+  --kc|--kubeconfig <KUBECONFIG_FILE> Path to the kubeconfig file to use for CLI requests.
                                       Required if not supplying --cluster_location,
                                       --cluster_name, --project_id in order to locate
                                       and connect to the intended cluster.
   --ctx|--context        <CONTEXT>    The name of the kubeconfig context to use.
+  --fleet_id             <FLEET ID>   The Fleet host project ID. Required for non-GCP
+                                      clusters. When not provided for GCP clusters, it
+                                      defaults to the cluster's project ID.
   -c|--ca                <CA>         The type of certificate authority to be
                                       used. Defaults to "mesh_ca" for install.
                                       Allowed values for <CA> are {citadel|mesh_ca|gcp_cas}.
@@ -2442,6 +2458,7 @@ OPTIONS:
   -p|--project_id        <ID>
   --kc|--kubeconfig      <KUBECONFIG_FILE>
   --ctx|--context        <CONTEXT>
+  --fleet_id             <FLEET ID>
   -c|--ca                <CA>
 
   -o|--option            <FILE NAME>
@@ -2754,7 +2771,7 @@ print-config_subcommand() {
 
   local USE_HUB_WIP; USE_HUB_WIP="$(context_get-option "USE_HUB_WIP")"
   if [[ "${USE_HUB_WIP}" -eq 1 ]]; then
-    populate_environ_info
+    populate_fleet_info
   fi
   print_config >&3
 }
@@ -2999,19 +3016,19 @@ configure_in_cluster_control_plane() {
 init_meshconfig() {
   local USE_HUB_WIP; USE_HUB_WIP="$(context_get-option "USE_HUB_WIP")"
   local HUB_MEMBERSHIP_ID; HUB_MEMBERSHIP_ID="$(context_get-option "HUB_MEMBERSHIP_ID")"
-  local ENVIRON_PROJECT_ID; ENVIRON_PROJECT_ID="$(context_get-option "ENVIRON_PROJECT_ID")"
+  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"
   local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
 
   info "Initializing meshconfig API..."
   if [[ "${USE_HUB_WIP}" -eq 1 ]]; then
-    populate_environ_info
-    info "Cluster has Membership ID ${HUB_MEMBERSHIP_ID} in the Hub of project ${ENVIRON_PROJECT_ID}"
-    if [[ "${ENVIRON_PROJECT_ID}" != "${PROJECT_ID}" ]]; then
+    populate_fleet_info
+    info "Cluster has Membership ID ${HUB_MEMBERSHIP_ID} in the Hub of project ${FLEET_ID}"
+    if [[ "${FLEET_ID}" != "${PROJECT_ID}" ]]; then
       info "Skip initializing meshconfig API as the Hub is not hosted in the project ${PROJECT_ID}"
       return 0
     fi
     # initialize replaces the existing Workload Identity Pools in the IAM binding, so we need to support both Hub and GKE Workload Identity Pools
-    local POST_DATA; POST_DATA='{"workloadIdentityPools":["'${ENVIRON_PROJECT_ID}'.hub.id.goog","'${ENVIRON_PROJECT_ID}'.svc.id.goog"]}'
+    local POST_DATA; POST_DATA='{"workloadIdentityPools":["'${FLEET_ID}'.hub.id.goog","'${FLEET_ID}'.svc.id.goog"]}'
     run_command curl --request POST --fail \
     --data "${POST_DATA}" -o /dev/null \
     "https://meshconfig.googleapis.com/v1alpha1/projects/${PROJECT_ID}:initialize" \
@@ -3081,10 +3098,11 @@ context_init() {
     "PROJECT_ID": "${PROJECT_ID:-}",
     "CLUSTER_NAME": "${CLUSTER_NAME:-}",
     "CLUSTER_LOCATION": "${CLUSTER_LOCATION:-}",
-    "PLATFORM": "${PLATFORM:-}",
-    "CA": "${CA:-}",
     "KUBECONFIG": "${KUBECONFIG_FILE:-}",
     "KUBECONFIG_SUPPLIED": "${KUBECONFIG_SUPPLIED:-0}",
+    "FLEET_ID": "${FLEET_ID:-}",
+    "CA": "${CA:-}",
+    "PLATFORM": "${PLATFORM:-}",
     "CONTEXT": "${CONTEXT:-}",
     "CUSTOM_OVERLAY": "${CUSTOM_OVERLAY:-}",
     "OPTIONAL_OVERLAY": "${OPTIONAL_OVERLAY:-}",
@@ -3118,7 +3136,7 @@ context_init() {
     "CUSTOM_CA": ${CUSTOM_CA:-0},
     "USE_HUB_WIP": ${USE_HUB_WIP:-0},
     "USE_VM": ${USE_VM:-0},
-    "ENVIRON_PROJECT_ID": "${ENVIRON_PROJECT_ID:-}",
+    "FLEET_ID": "${FLEET_ID:-}",
     "HUB_MEMBERSHIP_ID": "${HUB_MEMBERSHIP_ID:-}",
     "CUSTOM_REVISION": ${CUSTOM_REVISION:-0},
     "WI_ENABLED": ${WI_ENABLED:-0}
