Add environment variables to cloudbuild.yaml (#164)
* Add environment variables to cloudbuild.yaml

* Update citadel option for 1.7

* Update tests to point to 1.7.1 OSS

* Fix run_cli tests

* Add one retry for verifying ingress in tests

diff --git a/scripts/asm-installer/tests/run_basic_suite b/scripts/asm-installer/tests/run_basic_suite
--- a/scripts/asm-installer/tests/run_basic_suite
+++ b/scripts/asm-installer/tests/run_basic_suite
@@ -75,7 +75,6 @@ main() {
   echo "Performing a rolling restart of the demo app..."
   roll "${NAMESPACE}"
 
-
   local SUCCESS; SUCCESS=0;
   echo "Getting istio ingress IP..."
   GATEWAY="$(istio_ingress)"
@@ -84,6 +83,19 @@ main() {
   set +e
   verify_demo_app "${GATEWAY}" || SUCCESS=1
   set -e
+
+  if [[ "${SUCCESS}" -eq 1 ]]; then
+    echo "Failed to verify, restarting and trying again..."
+    roll "${NAMESPACE}"
+
+    echo "Getting istio ingress IP..."
+    GATEWAY="$(istio_ingress)"
+    echo "Got ${GATEWAY}"
+    echo "Verifying demo app via Istio ingress..."
+    set +e
+    verify_demo_app "${GATEWAY}" || SUCCESS=1
+    set -e
+  fi
 
   # Cluster teardown
   echo "Deleting cluster ${CLUSTER_NAME} and associated resources..."
