Download kpt when necessary (#774)

diff --git a/scripts/asm-installer/tests/run_cli_tests b/scripts/asm-installer/tests/run_cli_tests
--- a/scripts/asm-installer/tests/run_cli_tests
+++ b/scripts/asm-installer/tests/run_cli_tests
@@ -90,6 +90,9 @@ tar() {
 }
 
 kpt() {
+  if [[ "${1}" = "version" ]]; then
+    echo "1.0.0"
+  fi
   return 0
 }
 
@@ -520,6 +523,17 @@ EOF
   fi
   echo "***"
 
+  #################
+  # kpt should be downloaded if the environment version is not 0.x
+  #################
+
+  if ! needs_kpt; then
+    echo "needs_kpt is true when kpt is too new: FAIL"
+    ((++FAILURES))
+  else
+    echo "needs_kpt is true when kpt is too new: PASS"
+  fi
+  echo "***"
 
   #################
   echo "There were ${FAILURES} failures."
