Download kpt when necessary

diff --git a/scripts/asm-installer/tests/run_cli_tests b/scripts/asm-installer/tests/run_cli_tests
--- a/scripts/asm-installer/tests/run_cli_tests
+++ b/scripts/asm-installer/tests/run_cli_tests
@@ -106,6 +106,9 @@ tar() {
 }
 
 kpt() {
+  if [[ "${1}" = "version" ]]; then
+    echo "1.0.0"
+  fi
   return 0
 }
 
@@ -637,8 +640,8 @@ EOF
 
   WARNED=0
   FATAL_EXITS=0
-  AKPT=""
-  AGCLOUD="gcloud"
+  AKPT="kpt"
+  AGCLOUD=""
   AKUBECTL="kubectl"
   validate_cli_dependencies
   FATAL_EXITS=1
@@ -648,6 +651,18 @@ EOF
     ((++FAILURES))
   else
     echo "validate_cli_dependencies handles compatibility variables: PASS"
+  fi
+  echo "***"
+
+  #################
+  # kpt should be downloaded if the environment version is not 0.x
+  #################
+
+  if ! needs_kpt; then
+    echo "needs_kpt is true when kpt is too new: FAIL"
+    ((++FAILURES))
+  else
+    echo "needs_kpt is true when kpt is too new: PASS"
   fi
   echo "***"
 
