Have Scriptaro apply validation fix (#233) (#234)
* Have Scriptaro apply validation fix (#233)

* Add kpt setter to citadel Kptfile

diff --git a/scripts/asm-installer/tests/run_basic_suite b/scripts/asm-installer/tests/run_basic_suite
--- a/scripts/asm-installer/tests/run_basic_suite
+++ b/scripts/asm-installer/tests/run_basic_suite
@@ -85,6 +85,12 @@ main() {
   verify_demo_app "${GATEWAY}" || SUCCESS=1
   set -e
 
+  # check validation webhook
+  echo "Verifying istiod service exists..."
+  if ! does_istiod_exist; then
+    echo "Could not find istiod service."
+  fi
+
   # Cluster teardown
   echo "Deleting cluster ${CLUSTER_NAME} and associated resources..."
   cleanup "${PROJECT_ID}" "${CLUSTER_NAME}" "${CLUSTER_LOCATION}" "${NAMESPACE}"
