Have Scriptaro apply validation fix (#233)

diff --git a/scripts/asm-installer/tests/run_basic_suite b/scripts/asm-installer/tests/run_basic_suite
--- a/scripts/asm-installer/tests/run_basic_suite
+++ b/scripts/asm-installer/tests/run_basic_suite
@@ -97,6 +97,12 @@ main() {
     set -e
   fi
 
+  # check validation webhook
+  echo "Verifying istiod service exists..."
+  if ! does_istiod_exist; then
+    echo "Could not find istiod service."
+  fi
+
   # Cluster teardown
   echo "Deleting cluster ${CLUSTER_NAME} and associated resources..."
   cleanup "${PROJECT_ID}" "${CLUSTER_NAME}" "${CLUSTER_LOCATION}" "${NAMESPACE}"
