Small fix.

diff --git a/scripts/ca-migration/migrate_ca b/scripts/ca-migration/migrate_ca
--- a/scripts/ca-migration/migrate_ca
+++ b/scripts/ca-migration/migrate_ca
@@ -1,5 +1,29 @@
 #!/bin/bash
 
+MESHCA_SPIFFE_ENDPOINT=https://storage.googleapis.com/mesh-ca-resources/spiffe_bundle.json
+MESHCA_ROOT_CONFIG="    caCertificates:
+    - pem: |-"
+
+if ! istioctl &> /dev/null; then
+  echo "istioctl could not be found, please add istioctl into your PATH."
+  exit 1
+fi
+
+if ! jq --version &> /dev/null; then
+  echo "jq could not be found, please make sure it is installed."
+  exit 1
+fi
+
+if ! kubectl version &> /dev/null; then
+  echo "kubectl could not be found, please make sure it is installed."
+  exit 1
+fi
+
+if ! openssl version &> /dev/null; then
+  echo "openssl could not be found, please make sure it is installed."
+  exit 1
+fi
+
 declare -A rootmap
 
 add_to_rootmap() {
@@ -34,6 +58,8 @@ add_to_rootmap() {
   rootmap[$3]=${canames}
 }
 
+# $1: pod
+# $2: namespace
 get_issuer_ca() {
   local output
   local certchain
@@ -60,6 +86,9 @@ get_issuer_ca() {
   fi
 }
 
+# $1: pod
+# $2: namespace
+# $3: ROOTCA/default
 check_cert_in_pod() {
   local sn
 
@@ -72,14 +101,41 @@ check_cert_in_pod() {
     if [[ -z ${rootmap[${sn}]} ]]; then
       add_to_rootmap $1 $2 ${sn}
     fi
-    echo $1.$2 trusts [${rootmap[${sn}]}]
+    echo "$1.$2 trusts [${rootmap[${sn}]}]"
   else
     get_issuer_ca $1 $2
   fi
 
 }
 
-check_cert_in_namespace() {
+# $1: pod
+# $2: namespace
+check_trustdomain_in_pod() {
+  local meshca
+  local citadel
+
+  if [ "$1" = *"egress"* ]; then
+    meshca=$(istioctl pc cluster $1 -n $2 -o json | grep "spiffe" | grep "id.goog")
+    citadel=$(istioctl pc cluster $1 -n $2 -o json | grep "spiffe" | grep -v "id.goog")
+  else
+    meshca=$(istioctl pc cluster $1 -n $2 -o json | grep "spiffe" | grep "id.goog")
+    citadel=$(istioctl pc cluster $1 -n $2 -o json | grep "spiffe" | grep -v "id.goog")
+  fi
+  if [[ -z meshca ]]; then
+    echo "$1.$2 is MISSING trust domain for [MESHCA]"
+    return
+  fi
+  if [[ -z citadel ]]; then
+    echo "$1.$2 is MISSING trust domain for [CITADEL]"
+    return
+  fi
+  echo "$1.$2 trusts trust domains for [CITADEL MESHCA]"
+}
+
+# $1: namespace
+# $2: cert/trustdomain
+# $3: extra config
+check_in_namespace() {
   local pods
   local containers
 
@@ -88,40 +144,60 @@ check_cert_in_namespace() {
 	do
     containers=$(kubectl get pod ${pod} -n "$1" -o jsonpath=={.spec.containers.*.name})
     if [[ "${containers}" == *"istio-proxy"* ]]; then
-      check_cert_in_pod "${pod}" "$1" "$2"
+      if [[ "$2" = "cert" ]]; then
+        check_cert_in_pod "${pod}" "$1" "$3"
+      else
+        check_trustdomain_in_pod "${pod}" "$1"
+      fi
     fi
 	done
 }
 
-check_cert() {
+# $1: cert/trustdomain
+# $2: extra config
+check() {
   local ns
+
   ns=$(kubectl get ns -o jsonpath={.items..metadata.name})
   for n in ${ns}
   do
     if [ "$n" != "kube-system" ] && [ "$n" != "kube-public" ] && [ "$n" != "kube-node-lease" ]; then
       echo
       echo "Namespace: $n"
-      check_cert_in_namespace "$n" "$1"
+      check_in_namespace "$n" "$1" "$2"
     fi
   done
 }
 
-case $1 in
-  check-root-cert)
-    check_cert "ROOTCA"
-    ;;
-
-  check-workload-cert)
-    check_cert "default"
-    ;;
-  *)
-    echo "Usage: check-root-cert | check-workload-cert
+print_help_info() {
+  echo
+  echo "Usage: check-root-cert | check-workload-cert | check-trustdomain
 
 check-root-cert
   Check the root certificates loaded on each Envoy proxy.
 
 check-workload-cert
   Check the CA issuer for the workload certificates on each Envoy proxy.
+
+check-trustdomain
+  Check the trusted trust domains for the workloads.
 "
+
+}
+
+case $1 in
+  check-root-cert)
+    check "cert" "ROOTCA"
+    ;;
+
+  check-workload-cert)
+    check "cert" "default"
+    ;;
+
+  check-trustdomain)
+    check "trustdomain"
+    ;;
+  *)
+  print_help_info
 
 esac
